package ${iconPackage};

import java.util.Map;

import javafx.geometry.Rectangle2D;

import ${basePackage}.IconGeometry;
import ${typePackage}.GraphicType;

/**
 * Bounds for the main icon fragments that are not built within the bounding octagon.
 * <p>
 * APP-6E 8.1.3 exempts Control Measure symbols from the icon composition rules - they are map graphics drawn against the whole canvas rather than icons assembled inside the
 * octagon - and a few Cyberspace path and terrain graphics are the same kind of thing. Those elements carry {@link GraphicType#FREE_CANVAS}, which says only that no region rule
 * applies, so their extent has to be measured rather than derived. Every other icon takes {@link IconGeometry#OCTAGON} by rule, and a {@code FULL_FRAME} one takes its frame's
 * bounds, so neither appears here.
 * <p>
 * Generated by {@code FragmentMeasurer}; do not edit. Keyed by graphic identifier, which is the fragment's file stem.
 */
public final class IconBounds {

    private static final Map<String, Rectangle2D> BOUNDS = Map.ofEntries(
<#list iconBounds as identifier, rect>
        Map.entry("${identifier}", new Rectangle2D(${rect.minX?c}, ${rect.minY?c}, ${rect.width?c}, ${rect.height?c}))<#sep>,
</#list>);

    /**
     * The measured bounds of the fragment with this identifier, or the region its graphic type says it keeps within when it has none. A {@code FREE_CANVAS} element with no
     * measurement falls back to the whole canvas, the only answer that cannot clip it.
     */
    public static Rectangle2D lookup(String graphicIdentifier, GraphicType graphicType) {
        Rectangle2D measured = BOUNDS.get(graphicIdentifier);
        if (measured != null) {
            return measured;
        }
        return graphicType == GraphicType.FREE_CANVAS ? IconGeometry.CANVAS : IconGeometry.OCTAGON;
    }

    private IconBounds() {
    }

}
