//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 04:45:07 PM NZDT 
//


package nz.co.ctg.jmsfx.generator.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AreaLabelMethodType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AreaLabelMethodType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="NA"/>
 *     &lt;enumeration value="HorizontalInPolygon"/>
 *     &lt;enumeration value="StraightInPolygon"/>
 *     &lt;enumeration value="CurvedInPolygon"/>
 *     &lt;enumeration value="HorizontalAroundPolygon"/>
 *     &lt;enumeration value="RepeatAlongBoundary"/>
 *     &lt;enumeration value="CurvedAroundPolygon"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AreaLabelMethodType")
@XmlEnum
public enum AreaLabelMethodType {

    NA("NA"),
    @XmlEnumValue("HorizontalInPolygon")
    HORIZONTAL_IN_POLYGON("HorizontalInPolygon"),
    @XmlEnumValue("StraightInPolygon")
    STRAIGHT_IN_POLYGON("StraightInPolygon"),
    @XmlEnumValue("CurvedInPolygon")
    CURVED_IN_POLYGON("CurvedInPolygon"),
    @XmlEnumValue("HorizontalAroundPolygon")
    HORIZONTAL_AROUND_POLYGON("HorizontalAroundPolygon"),
    @XmlEnumValue("RepeatAlongBoundary")
    REPEAT_ALONG_BOUNDARY("RepeatAlongBoundary"),
    @XmlEnumValue("CurvedAroundPolygon")
    CURVED_AROUND_POLYGON("CurvedAroundPolygon");
    private final String value;

    AreaLabelMethodType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AreaLabelMethodType fromValue(String v) {
        for (AreaLabelMethodType c: AreaLabelMethodType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
