//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 04:45:07 PM NZDT 
//


package nz.co.ctg.jmsfx.generator.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for FieldListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FieldListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Field" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{http://disa.mil/JointMilSyML.xsd}IdentifierAttributeGroup"/>
 *                 &lt;attribute name="Type" type="{http://disa.mil/JointMilSyML.xsd}AttributeTypeType" />
 *                 &lt;attribute name="AmplifierID" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                 &lt;attribute name="X" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *                 &lt;attribute name="Y" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FieldListType", propOrder = {
    "field"
})
public class FieldListType {

    @XmlElement(name = "Field")
    protected List<FieldListType.Field> field;

    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FieldListType.Field }
     * 
     * 
     */
    public List<FieldListType.Field> getField() {
        if (field == null) {
            field = new ArrayList<FieldListType.Field>();
        }
        return this.field;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{http://disa.mil/JointMilSyML.xsd}IdentifierAttributeGroup"/>
     *       &lt;attribute name="Type" type="{http://disa.mil/JointMilSyML.xsd}AttributeTypeType" />
     *       &lt;attribute name="AmplifierID" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *       &lt;attribute name="X" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
     *       &lt;attribute name="Y" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Field {

        @XmlAttribute(name = "Type")
        protected AttributeTypeType type;
        @XmlAttribute(name = "AmplifierID", required = true)
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected Object amplifierID;
        @XmlAttribute(name = "X")
        protected Integer x;
        @XmlAttribute(name = "Y")
        protected Integer y;
        @XmlAttribute(name = "ID", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;
        @XmlAttribute(name = "Label")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String label;
        @XmlAttribute(name = "LabelAlias")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String labelAlias;
        @XmlAttribute(name = "Description")
        protected String description;
        @XmlAttribute(name = "Remarks")
        protected String remarks;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link AttributeTypeType }
         *     
         */
        public AttributeTypeType getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link AttributeTypeType }
         *     
         */
        public void setType(AttributeTypeType value) {
            this.type = value;
        }

        /**
         * Gets the value of the amplifierID property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getAmplifierID() {
            return amplifierID;
        }

        /**
         * Sets the value of the amplifierID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setAmplifierID(Object value) {
            this.amplifierID = value;
        }

        /**
         * Gets the value of the x property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getX() {
            if (x == null) {
                return  0;
            } else {
                return x;
            }
        }

        /**
         * Sets the value of the x property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setX(Integer value) {
            this.x = value;
        }

        /**
         * Gets the value of the y property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getY() {
            if (y == null) {
                return  0;
            } else {
                return y;
            }
        }

        /**
         * Sets the value of the y property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setY(Integer value) {
            this.y = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabel(String value) {
            this.label = value;
        }

        /**
         * Gets the value of the labelAlias property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabelAlias() {
            if (labelAlias == null) {
                return "";
            } else {
                return labelAlias;
            }
        }

        /**
         * Sets the value of the labelAlias property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabelAlias(String value) {
            this.labelAlias = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the remarks property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemarks() {
            return remarks;
        }

        /**
         * Sets the value of the remarks property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemarks(String value) {
            this.remarks = value;
        }

    }

}
