//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 04:45:07 PM NZDT 
//


package nz.co.ctg.jmsfx.generator.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LabelUnitType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LabelUnitType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Map"/>
 *     &lt;enumeration value="MM"/>
 *     &lt;enumeration value="Inch"/>
 *     &lt;enumeration value="Point"/>
 *     &lt;enumeration value="Percentage"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LabelUnitType")
@XmlEnum
public enum LabelUnitType {

    @XmlEnumValue("Map")
    MAP("Map"),
    MM("MM"),
    @XmlEnumValue("Inch")
    INCH("Inch"),
    @XmlEnumValue("Point")
    POINT("Point"),
    @XmlEnumValue("Percentage")
    PERCENTAGE("Percentage");
    private final String value;

    LabelUnitType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LabelUnitType fromValue(String v) {
        for (LabelUnitType c: LabelUnitType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
