//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 04:45:07 PM NZDT 
//


package nz.co.ctg.jmsfx.generator.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LabelAnchorPointType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LabelAnchorPointType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="CenterOfLabel"/>
 *     &lt;enumeration value="NearestSideOfLabel"/>
 *     &lt;enumeration value="FurthestSideOfLabel"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LabelAnchorPointType")
@XmlEnum
public enum LabelAnchorPointType {

    @XmlEnumValue("CenterOfLabel")
    CENTER_OF_LABEL("CenterOfLabel"),
    @XmlEnumValue("NearestSideOfLabel")
    NEAREST_SIDE_OF_LABEL("NearestSideOfLabel"),
    @XmlEnumValue("FurthestSideOfLabel")
    FURTHEST_SIDE_OF_LABEL("FurthestSideOfLabel");
    private final String value;

    LabelAnchorPointType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LabelAnchorPointType fromValue(String v) {
        for (LabelAnchorPointType c: LabelAnchorPointType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
