//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 04:45:07 PM NZDT 
//


package nz.co.ctg.jmsfx.generator.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LabelRuleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LabelRuleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Point"/>
 *     &lt;enumeration value="Line"/>
 *     &lt;enumeration value="Area"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LabelRuleType")
@XmlEnum
public enum LabelRuleType {

    @XmlEnumValue("Point")
    POINT("Point"),
    @XmlEnumValue("Line")
    LINE("Line"),
    @XmlEnumValue("Area")
    AREA("Area");
    private final String value;

    LabelRuleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LabelRuleType fromValue(String v) {
        for (LabelRuleType c: LabelRuleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
