//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 04:45:07 PM NZDT 
//


package nz.co.ctg.jmsfx.generator.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for LegacyLetterCodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LegacyLetterCodeType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://disa.mil/JointMilSyML.xsd>SingleLetterType">
 *       &lt;attGroup ref="{http://disa.mil/JointMilSyML.xsd}NameAttributeGroup"/>
 *       &lt;attribute name="CodingSchemeLetter" type="{http://www.w3.org/2001/XMLSchema}token" default="" />
 *       &lt;attribute name="StandardIdentityOverride" type="{http://www.w3.org/2001/XMLSchema}token" default="" />
 *       &lt;attribute name="BattleDimensionLetter" type="{http://www.w3.org/2001/XMLSchema}token" default="" />
 *       &lt;attribute name="FirstFunctionLetter" type="{http://www.w3.org/2001/XMLSchema}token" default="" />
 *       &lt;attribute name="Function" type="{http://www.w3.org/2001/XMLSchema}token" default="" />
 *       &lt;attribute name="IsPlanned" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="Graphic" type="{http://www.w3.org/2001/XMLSchema}token" default="" />
 *       &lt;attribute name="LimitUseTo" type="{http://www.w3.org/2001/XMLSchema}token" default="" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LegacyLetterCodeType", propOrder = {
    "value"
})
public class LegacyLetterCodeType {

    @XmlValue
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String value;
    @XmlAttribute(name = "CodingSchemeLetter")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String codingSchemeLetter;
    @XmlAttribute(name = "StandardIdentityOverride")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String standardIdentityOverride;
    @XmlAttribute(name = "BattleDimensionLetter")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String battleDimensionLetter;
    @XmlAttribute(name = "FirstFunctionLetter")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String firstFunctionLetter;
    @XmlAttribute(name = "Function")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String function;
    @XmlAttribute(name = "IsPlanned")
    protected Boolean isPlanned;
    @XmlAttribute(name = "Graphic")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String graphic;
    @XmlAttribute(name = "LimitUseTo")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String limitUseTo;
    @XmlAttribute(name = "Name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String name;
    @XmlAttribute(name = "Label")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String label;
    @XmlAttribute(name = "LabelAlias")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String labelAlias;
    @XmlAttribute(name = "Description")
    protected String description;
    @XmlAttribute(name = "Remarks")
    protected String remarks;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the codingSchemeLetter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodingSchemeLetter() {
        if (codingSchemeLetter == null) {
            return "";
        } else {
            return codingSchemeLetter;
        }
    }

    /**
     * Sets the value of the codingSchemeLetter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodingSchemeLetter(String value) {
        this.codingSchemeLetter = value;
    }

    /**
     * Gets the value of the standardIdentityOverride property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandardIdentityOverride() {
        if (standardIdentityOverride == null) {
            return "";
        } else {
            return standardIdentityOverride;
        }
    }

    /**
     * Sets the value of the standardIdentityOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandardIdentityOverride(String value) {
        this.standardIdentityOverride = value;
    }

    /**
     * Gets the value of the battleDimensionLetter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBattleDimensionLetter() {
        if (battleDimensionLetter == null) {
            return "";
        } else {
            return battleDimensionLetter;
        }
    }

    /**
     * Sets the value of the battleDimensionLetter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBattleDimensionLetter(String value) {
        this.battleDimensionLetter = value;
    }

    /**
     * Gets the value of the firstFunctionLetter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstFunctionLetter() {
        if (firstFunctionLetter == null) {
            return "";
        } else {
            return firstFunctionLetter;
        }
    }

    /**
     * Sets the value of the firstFunctionLetter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstFunctionLetter(String value) {
        this.firstFunctionLetter = value;
    }

    /**
     * Gets the value of the function property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunction() {
        if (function == null) {
            return "";
        } else {
            return function;
        }
    }

    /**
     * Sets the value of the function property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunction(String value) {
        this.function = value;
    }

    /**
     * Gets the value of the isPlanned property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsPlanned() {
        if (isPlanned == null) {
            return true;
        } else {
            return isPlanned;
        }
    }

    /**
     * Sets the value of the isPlanned property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPlanned(Boolean value) {
        this.isPlanned = value;
    }

    /**
     * Gets the value of the graphic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGraphic() {
        if (graphic == null) {
            return "";
        } else {
            return graphic;
        }
    }

    /**
     * Sets the value of the graphic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGraphic(String value) {
        this.graphic = value;
    }

    /**
     * Gets the value of the limitUseTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLimitUseTo() {
        if (limitUseTo == null) {
            return "";
        } else {
            return limitUseTo;
        }
    }

    /**
     * Sets the value of the limitUseTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLimitUseTo(String value) {
        this.limitUseTo = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the labelAlias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelAlias() {
        if (labelAlias == null) {
            return "";
        } else {
            return labelAlias;
        }
    }

    /**
     * Sets the value of the labelAlias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelAlias(String value) {
        this.labelAlias = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

}
