//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 04:45:07 PM NZDT 
//


package nz.co.ctg.jmsfx.generator.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LineLabelMethodType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LineLabelMethodType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="NA"/>
 *     &lt;enumeration value="CenteredHorizontalOnLine"/>
 *     &lt;enumeration value="CenteredStraightOnLine"/>
 *     &lt;enumeration value="CenteredCurvedOnLine"/>
 *     &lt;enumeration value="CenteredPerpendicularOnLine"/>
 *     &lt;enumeration value="OffsetHorizontalFromLine"/>
 *     &lt;enumeration value="OffsetStraightFromLine"/>
 *     &lt;enumeration value="OffsetCurvedFromLine"/>
 *     &lt;enumeration value="OffsetPerpendicularFromLine"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LineLabelMethodType")
@XmlEnum
public enum LineLabelMethodType {

    NA("NA"),
    @XmlEnumValue("CenteredHorizontalOnLine")
    CENTERED_HORIZONTAL_ON_LINE("CenteredHorizontalOnLine"),
    @XmlEnumValue("CenteredStraightOnLine")
    CENTERED_STRAIGHT_ON_LINE("CenteredStraightOnLine"),
    @XmlEnumValue("CenteredCurvedOnLine")
    CENTERED_CURVED_ON_LINE("CenteredCurvedOnLine"),
    @XmlEnumValue("CenteredPerpendicularOnLine")
    CENTERED_PERPENDICULAR_ON_LINE("CenteredPerpendicularOnLine"),
    @XmlEnumValue("OffsetHorizontalFromLine")
    OFFSET_HORIZONTAL_FROM_LINE("OffsetHorizontalFromLine"),
    @XmlEnumValue("OffsetStraightFromLine")
    OFFSET_STRAIGHT_FROM_LINE("OffsetStraightFromLine"),
    @XmlEnumValue("OffsetCurvedFromLine")
    OFFSET_CURVED_FROM_LINE("OffsetCurvedFromLine"),
    @XmlEnumValue("OffsetPerpendicularFromLine")
    OFFSET_PERPENDICULAR_FROM_LINE("OffsetPerpendicularFromLine");
    private final String value;

    LineLabelMethodType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LineLabelMethodType fromValue(String v) {
        for (LineLabelMethodType c: LineLabelMethodType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
