//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 04:45:07 PM NZDT 
//


package nz.co.ctg.jmsfx.generator.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ModifiersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModifiersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Modifier" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ModifierCode" type="{http://disa.mil/JointMilSyML.xsd}DoubleDigitType"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{http://disa.mil/JointMilSyML.xsd}GraphicIdentifierAttributeGroup"/>
 *                 &lt;attribute name="Category" type="{http://www.w3.org/2001/XMLSchema}token" default="" />
 *                 &lt;attribute name="CategoryAlias" type="{http://www.w3.org/2001/XMLSchema}token" default="" />
 *                 &lt;attribute name="LimitUseTo" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *                 &lt;attribute name="Standard" type="{http://disa.mil/JointMilSyML.xsd}StandardType" default="ALL" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModifiersType", propOrder = {
    "modifier"
})
public class ModifiersType {

    @XmlElement(name = "Modifier", required = true)
    protected List<ModifiersType.Modifier> modifier;

    /**
     * Gets the value of the modifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModifiersType.Modifier }
     * 
     * 
     */
    public List<ModifiersType.Modifier> getModifier() {
        if (modifier == null) {
            modifier = new ArrayList<ModifiersType.Modifier>();
        }
        return this.modifier;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ModifierCode" type="{http://disa.mil/JointMilSyML.xsd}DoubleDigitType"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://disa.mil/JointMilSyML.xsd}GraphicIdentifierAttributeGroup"/>
     *       &lt;attribute name="Category" type="{http://www.w3.org/2001/XMLSchema}token" default="" />
     *       &lt;attribute name="CategoryAlias" type="{http://www.w3.org/2001/XMLSchema}token" default="" />
     *       &lt;attribute name="LimitUseTo" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
     *       &lt;attribute name="Standard" type="{http://disa.mil/JointMilSyML.xsd}StandardType" default="ALL" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "modifierCode"
    })
    public static class Modifier {

        @XmlElement(name = "ModifierCode", required = true)
        protected DoubleDigitType modifierCode;
        @XmlAttribute(name = "Category")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String category;
        @XmlAttribute(name = "CategoryAlias")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String categoryAlias;
        @XmlAttribute(name = "LimitUseTo")
        @XmlIDREF
        @XmlSchemaType(name = "IDREFS")
        protected List<Object> limitUseTo;
        @XmlAttribute(name = "Standard")
        protected StandardType standard;
        @XmlAttribute(name = "ID", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;
        @XmlAttribute(name = "Label")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String label;
        @XmlAttribute(name = "LabelAlias")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String labelAlias;
        @XmlAttribute(name = "Description")
        protected String description;
        @XmlAttribute(name = "Remarks")
        protected String remarks;
        @XmlAttribute(name = "Graphic")
        @XmlSchemaType(name = "anyURI")
        protected String graphic;

        /**
         * Gets the value of the modifierCode property.
         * 
         * @return
         *     possible object is
         *     {@link DoubleDigitType }
         *     
         */
        public DoubleDigitType getModifierCode() {
            return modifierCode;
        }

        /**
         * Sets the value of the modifierCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link DoubleDigitType }
         *     
         */
        public void setModifierCode(DoubleDigitType value) {
            this.modifierCode = value;
        }

        /**
         * Gets the value of the category property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCategory() {
            if (category == null) {
                return "";
            } else {
                return category;
            }
        }

        /**
         * Sets the value of the category property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCategory(String value) {
            this.category = value;
        }

        /**
         * Gets the value of the categoryAlias property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCategoryAlias() {
            if (categoryAlias == null) {
                return "";
            } else {
                return categoryAlias;
            }
        }

        /**
         * Sets the value of the categoryAlias property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCategoryAlias(String value) {
            this.categoryAlias = value;
        }

        /**
         * Gets the value of the limitUseTo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the limitUseTo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLimitUseTo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * 
         * 
         */
        public List<Object> getLimitUseTo() {
            if (limitUseTo == null) {
                limitUseTo = new ArrayList<Object>();
            }
            return this.limitUseTo;
        }

        /**
         * Gets the value of the standard property.
         * 
         * @return
         *     possible object is
         *     {@link StandardType }
         *     
         */
        public StandardType getStandard() {
            if (standard == null) {
                return StandardType.ALL;
            } else {
                return standard;
            }
        }

        /**
         * Sets the value of the standard property.
         * 
         * @param value
         *     allowed object is
         *     {@link StandardType }
         *     
         */
        public void setStandard(StandardType value) {
            this.standard = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabel(String value) {
            this.label = value;
        }

        /**
         * Gets the value of the labelAlias property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabelAlias() {
            if (labelAlias == null) {
                return "";
            } else {
                return labelAlias;
            }
        }

        /**
         * Sets the value of the labelAlias property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabelAlias(String value) {
            this.labelAlias = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the remarks property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemarks() {
            return remarks;
        }

        /**
         * Sets the value of the remarks property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemarks(String value) {
            this.remarks = value;
        }

        /**
         * Gets the value of the graphic property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGraphic() {
            return graphic;
        }

        /**
         * Sets the value of the graphic property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGraphic(String value) {
            this.graphic = value;
        }

    }

}
