//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 04:45:07 PM NZDT 
//


package nz.co.ctg.jmsfx.generator.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MultiPartOptionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MultiPartOptionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="OneLabelPerFeature"/>
 *     &lt;enumeration value="OneLabelPerPart"/>
 *     &lt;enumeration value="OneLabelPerSegment"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MultiPartOptionType")
@XmlEnum
public enum MultiPartOptionType {

    @XmlEnumValue("OneLabelPerFeature")
    ONE_LABEL_PER_FEATURE("OneLabelPerFeature"),
    @XmlEnumValue("OneLabelPerPart")
    ONE_LABEL_PER_PART("OneLabelPerPart"),
    @XmlEnumValue("OneLabelPerSegment")
    ONE_LABEL_PER_SEGMENT("OneLabelPerSegment");
    private final String value;

    MultiPartOptionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MultiPartOptionType fromValue(String v) {
        for (MultiPartOptionType c: MultiPartOptionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
