//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.03 at 04:45:07 PM NZDT
//

package nz.co.ctg.jmsfx.generator.schema;

import javax.xml.namespace.QName;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {

    private final static QName _Entity_QNAME = new QName("http://disa.mil/JointMilSyML.xsd", "Entity");
    private final static QName _DoubleDigitTypeDigitOne_QNAME = new QName("http://disa.mil/JointMilSyML.xsd", "DigitOne");
    private final static QName _DoubleDigitTypeDigitTwo_QNAME = new QName("http://disa.mil/JointMilSyML.xsd", "DigitTwo");

    public ObjectFactory() {
    }

    public DoubleDigitType createDoubleDigitType() {
        return new DoubleDigitType();
    }

    @XmlElementDecl(namespace = "http://disa.mil/JointMilSyML.xsd", name = "DigitOne", scope = DoubleDigitType.class, defaultValue = "0")
    public JAXBElement<Integer> createDoubleDigitTypeDigitOne(Integer value) {
        return new JAXBElement<>(_DoubleDigitTypeDigitOne_QNAME, Integer.class, DoubleDigitType.class, value);
    }

    @XmlElementDecl(namespace = "http://disa.mil/JointMilSyML.xsd", name = "DigitTwo", scope = DoubleDigitType.class, defaultValue = "0")
    public JAXBElement<Integer> createDoubleDigitTypeDigitTwo(Integer value) {
        return new JAXBElement<>(_DoubleDigitTypeDigitTwo_QNAME, Integer.class, DoubleDigitType.class, value);
    }

    @XmlElementDecl(namespace = "http://disa.mil/JointMilSyML.xsd", name = "Entity")
    public JAXBElement<nz.co.ctg.jmsfx.generator.schema.EntityType> createEntity(nz.co.ctg.jmsfx.generator.schema.EntityType value) {
        return new JAXBElement<>(_Entity_QNAME, nz.co.ctg.jmsfx.generator.schema.EntityType.class, null, value);
    }

    public EntitySubTypeType createEntitySubTypeType() {
        return new EntitySubTypeType();
    }

    public nz.co.ctg.jmsfx.generator.schema.EntityType createEntityType() {
        return new nz.co.ctg.jmsfx.generator.schema.EntityType();
    }

    public FieldListType createFieldListType() {
        return new FieldListType();
    }

    public FieldListType.Field createFieldListTypeField() {
        return new FieldListType.Field();
    }

    public Library createLibrary() {
        return new Library();
    }

    public Library.AmplifierGroups createLibraryAmplifierGroups() {
        return new Library.AmplifierGroups();
    }

    public Library.AmplifierGroups.AmplifierGroup createLibraryAmplifierGroupsAmplifierGroup() {
        return new Library.AmplifierGroups.AmplifierGroup();
    }

    public Library.AmplifierGroups.AmplifierGroup.Amplifiers createLibraryAmplifierGroupsAmplifierGroupAmplifiers() {
        return new Library.AmplifierGroups.AmplifierGroup.Amplifiers();
    }

    public Library.AmplifierGroups.AmplifierGroup.Amplifiers.Amplifier createLibraryAmplifierGroupsAmplifierGroupAmplifiersAmplifier() {
        return new Library.AmplifierGroups.AmplifierGroup.Amplifiers.Amplifier();
    }

    public Library.AmplifierGroups.AmplifierGroup.Amplifiers.Amplifier.Graphics createLibraryAmplifierGroupsAmplifierGroupAmplifiersAmplifierGraphics() {
        return new Library.AmplifierGroups.AmplifierGroup.Amplifiers.Amplifier.Graphics();
    }

    public Library.AmplifierGroups.AmplifierGroup.Amplifiers.Amplifier.Graphics.Graphic createLibraryAmplifierGroupsAmplifierGroupAmplifiersAmplifierGraphicsGraphic() {
        return new Library.AmplifierGroups.AmplifierGroup.Amplifiers.Amplifier.Graphics.Graphic();
    }

    public Library.Amplifiers createLibraryAmplifiers() {
        return new Library.Amplifiers();
    }

    public Library.Amplifiers.Amplifier createLibraryAmplifiersAmplifier() {
        return new Library.Amplifiers.Amplifier();
    }

    public Library.Amplifiers.Amplifier.Values createLibraryAmplifiersAmplifierValues() {
        return new Library.Amplifiers.Amplifier.Values();
    }

    public Library.Amplifiers.Amplifier.Values.Value createLibraryAmplifiersAmplifierValuesValue() {
        return new Library.Amplifiers.Amplifier.Values.Value();
    }

    public Library.Contexts createLibraryContexts() {
        return new Library.Contexts();
    }

    public Library.Contexts.Context createLibraryContextsContext() {
        return new Library.Contexts.Context();
    }

    public Library.Dimensions createLibraryDimensions() {
        return new Library.Dimensions();
    }

    public Library.Dimensions.Dimension createLibraryDimensionsDimension() {
        return new Library.Dimensions.Dimension();
    }

    public Library.Dimensions.Dimension.SymbolSets createLibraryDimensionsDimensionSymbolSets() {
        return new Library.Dimensions.Dimension.SymbolSets();
    }

    public Library.Dimensions.Dimension.SymbolSets.SymbolSetRef createLibraryDimensionsDimensionSymbolSetsSymbolSetRef() {
        return new Library.Dimensions.Dimension.SymbolSets.SymbolSetRef();
    }

    public Library.DrawRules createLibraryDrawRules() {
        return new Library.DrawRules();
    }

    public Library.DrawRules.DrawRule createLibraryDrawRulesDrawRule() {
        return new Library.DrawRules.DrawRule();
    }

    public Library.Geometries createLibraryGeometries() {
        return new Library.Geometries();
    }

    public Library.Geometries.Geometry createLibraryGeometriesGeometry() {
        return new Library.Geometries.Geometry();
    }

    public Library.HQTFDummies createLibraryHQTFDummies() {
        return new Library.HQTFDummies();
    }

    public Library.HQTFDummies.HQTFDummy createLibraryHQTFDummiesHQTFDummy() {
        return new Library.HQTFDummies.HQTFDummy();
    }

    public Library.HQTFDummies.HQTFDummy.Graphics createLibraryHQTFDummiesHQTFDummyGraphics() {
        return new Library.HQTFDummies.HQTFDummy.Graphics();
    }

    public Library.HQTFDummies.HQTFDummy.Graphics.Graphic createLibraryHQTFDummiesHQTFDummyGraphicsGraphic() {
        return new Library.HQTFDummies.HQTFDummy.Graphics.Graphic();
    }

    public Library.LabelRules createLibraryLabelRules() {
        return new Library.LabelRules();
    }

    public Library.LabelRules.LabelRule createLibraryLabelRulesLabelRule() {
        return new Library.LabelRules.LabelRule();
    }

    public Library.StandardIdentities createLibraryStandardIdentities() {
        return new Library.StandardIdentities();
    }

    public Library.StandardIdentities.StandardIdentity createLibraryStandardIdentitiesStandardIdentity() {
        return new Library.StandardIdentities.StandardIdentity();
    }

    public Library.StandardIdentityGroups createLibraryStandardIdentityGroups() {
        return new Library.StandardIdentityGroups();
    }

    public Library.StandardIdentityGroups.StandardIdentityGroup createLibraryStandardIdentityGroupsStandardIdentityGroup() {
        return new Library.StandardIdentityGroups.StandardIdentityGroup();
    }

    public Library.Statuses createLibraryStatuses() {
        return new Library.Statuses();
    }

    public Library.Statuses.Status createLibraryStatusesStatus() {
        return new Library.Statuses.Status();
    }

    public Library.Statuses.Status.Graphics createLibraryStatusesStatusGraphics() {
        return new Library.Statuses.Status.Graphics();
    }

    public Library.Statuses.Status.Graphics.Graphic createLibraryStatusesStatusGraphicsGraphic() {
        return new Library.Statuses.Status.Graphics.Graphic();
    }

    public Library.Versions createLibraryVersions() {
        return new Library.Versions();
    }

    public Library.Versions.Version createLibraryVersionsVersion() {
        return new Library.Versions.Version();
    }

    public ModifiersType createModifiersType() {
        return new ModifiersType();
    }

    public ModifiersType.Modifier createModifiersTypeModifier() {
        return new ModifiersType.Modifier();
    }

    public SymbolSet createSymbolSet() {
        return new SymbolSet();
    }

    public SymbolSet.Entities createSymbolSetEntities() {
        return new SymbolSet.Entities();
    }

    public SymbolSet.Entities.Entity createSymbolSetEntitiesEntity() {
        return new SymbolSet.Entities.Entity();
    }

    public SymbolSet.Entities.Entity.EntityTypes createSymbolSetEntitiesEntityEntityTypes() {
        return new SymbolSet.Entities.Entity.EntityTypes();
    }

    public SymbolSet.Entities.Entity.EntityTypes.EntityType createSymbolSetEntitiesEntityEntityTypesEntityType() {
        return new SymbolSet.Entities.Entity.EntityTypes.EntityType();
    }

    public SymbolSet.Entities.Entity.EntityTypes.EntityType.EntitySubTypes createSymbolSetEntitiesEntityEntityTypesEntityTypeEntitySubTypes() {
        return new SymbolSet.Entities.Entity.EntityTypes.EntityType.EntitySubTypes();
    }

    public SymbolSet.SpecialEntitySubTypes createSymbolSetSpecialEntitySubTypes() {
        return new SymbolSet.SpecialEntitySubTypes();
    }

    public Tags createTags() {
        return new Tags();
    }

}
