//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 04:45:07 PM NZDT 
//


package nz.co.ctg.jmsfx.generator.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nz.co.ctg.hallux.generator.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LegacyEntity_QNAME = new QName("http://disa.mil/JointMilSyML.xsd", "LegacyEntity");
    private final static QName _Entity_QNAME = new QName("http://disa.mil/JointMilSyML.xsd", "Entity");
    private final static QName _DoubleDigitTypeDigitOne_QNAME = new QName("http://disa.mil/JointMilSyML.xsd", "DigitOne");
    private final static QName _DoubleDigitTypeDigitTwo_QNAME = new QName("http://disa.mil/JointMilSyML.xsd", "DigitTwo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nz.co.ctg.hallux.generator.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SymbolSet }
     * 
     */
    public SymbolSet createSymbolSet() {
        return new SymbolSet();
    }

    /**
     * Create an instance of {@link Library }
     * 
     */
    public Library createLibrary() {
        return new Library();
    }

    /**
     * Create an instance of {@link FieldListType }
     * 
     */
    public FieldListType createFieldListType() {
        return new FieldListType();
    }

    /**
     * Create an instance of {@link Library.AmplifierGroups }
     * 
     */
    public Library.AmplifierGroups createLibraryAmplifierGroups() {
        return new Library.AmplifierGroups();
    }

    /**
     * Create an instance of {@link Library.AmplifierGroups.AmplifierGroup }
     * 
     */
    public Library.AmplifierGroups.AmplifierGroup createLibraryAmplifierGroupsAmplifierGroup() {
        return new Library.AmplifierGroups.AmplifierGroup();
    }

    /**
     * Create an instance of {@link Library.AmplifierGroups.AmplifierGroup.Amplifiers }
     * 
     */
    public Library.AmplifierGroups.AmplifierGroup.Amplifiers createLibraryAmplifierGroupsAmplifierGroupAmplifiers() {
        return new Library.AmplifierGroups.AmplifierGroup.Amplifiers();
    }

    /**
     * Create an instance of {@link Library.AmplifierGroups.AmplifierGroup.Amplifiers.Amplifier }
     * 
     */
    public Library.AmplifierGroups.AmplifierGroup.Amplifiers.Amplifier createLibraryAmplifierGroupsAmplifierGroupAmplifiersAmplifier() {
        return new Library.AmplifierGroups.AmplifierGroup.Amplifiers.Amplifier();
    }

    /**
     * Create an instance of {@link Library.AmplifierGroups.AmplifierGroup.Amplifiers.Amplifier.Graphics }
     * 
     */
    public Library.AmplifierGroups.AmplifierGroup.Amplifiers.Amplifier.Graphics createLibraryAmplifierGroupsAmplifierGroupAmplifiersAmplifierGraphics() {
        return new Library.AmplifierGroups.AmplifierGroup.Amplifiers.Amplifier.Graphics();
    }

    /**
     * Create an instance of {@link Library.HQTFDummies }
     * 
     */
    public Library.HQTFDummies createLibraryHQTFDummies() {
        return new Library.HQTFDummies();
    }

    /**
     * Create an instance of {@link Library.HQTFDummies.HQTFDummy }
     * 
     */
    public Library.HQTFDummies.HQTFDummy createLibraryHQTFDummiesHQTFDummy() {
        return new Library.HQTFDummies.HQTFDummy();
    }

    /**
     * Create an instance of {@link Library.HQTFDummies.HQTFDummy.Graphics }
     * 
     */
    public Library.HQTFDummies.HQTFDummy.Graphics createLibraryHQTFDummiesHQTFDummyGraphics() {
        return new Library.HQTFDummies.HQTFDummy.Graphics();
    }

    /**
     * Create an instance of {@link Library.Statuses }
     * 
     */
    public Library.Statuses createLibraryStatuses() {
        return new Library.Statuses();
    }

    /**
     * Create an instance of {@link Library.Statuses.Status }
     * 
     */
    public Library.Statuses.Status createLibraryStatusesStatus() {
        return new Library.Statuses.Status();
    }

    /**
     * Create an instance of {@link Library.Statuses.Status.Graphics }
     * 
     */
    public Library.Statuses.Status.Graphics createLibraryStatusesStatusGraphics() {
        return new Library.Statuses.Status.Graphics();
    }

    /**
     * Create an instance of {@link Library.Affiliations }
     * 
     */
    public Library.Affiliations createLibraryAffiliations() {
        return new Library.Affiliations();
    }

    /**
     * Create an instance of {@link Library.Affiliations.Affiliation }
     * 
     */
    public Library.Affiliations.Affiliation createLibraryAffiliationsAffiliation() {
        return new Library.Affiliations.Affiliation();
    }

    /**
     * Create an instance of {@link Library.Dimensions }
     * 
     */
    public Library.Dimensions createLibraryDimensions() {
        return new Library.Dimensions();
    }

    /**
     * Create an instance of {@link Library.Dimensions.Dimension }
     * 
     */
    public Library.Dimensions.Dimension createLibraryDimensionsDimension() {
        return new Library.Dimensions.Dimension();
    }

    /**
     * Create an instance of {@link Library.Dimensions.Dimension.SymbolSets }
     * 
     */
    public Library.Dimensions.Dimension.SymbolSets createLibraryDimensionsDimensionSymbolSets() {
        return new Library.Dimensions.Dimension.SymbolSets();
    }

    /**
     * Create an instance of {@link Library.StandardIdentityGroups }
     * 
     */
    public Library.StandardIdentityGroups createLibraryStandardIdentityGroups() {
        return new Library.StandardIdentityGroups();
    }

    /**
     * Create an instance of {@link Library.StandardIdentities }
     * 
     */
    public Library.StandardIdentities createLibraryStandardIdentities() {
        return new Library.StandardIdentities();
    }

    /**
     * Create an instance of {@link Library.Contexts }
     * 
     */
    public Library.Contexts createLibraryContexts() {
        return new Library.Contexts();
    }

    /**
     * Create an instance of {@link Library.Versions }
     * 
     */
    public Library.Versions createLibraryVersions() {
        return new Library.Versions();
    }

    /**
     * Create an instance of {@link Library.Amplifiers }
     * 
     */
    public Library.Amplifiers createLibraryAmplifiers() {
        return new Library.Amplifiers();
    }

    /**
     * Create an instance of {@link Library.Amplifiers.Amplifier }
     * 
     */
    public Library.Amplifiers.Amplifier createLibraryAmplifiersAmplifier() {
        return new Library.Amplifiers.Amplifier();
    }

    /**
     * Create an instance of {@link Library.Amplifiers.Amplifier.Values }
     * 
     */
    public Library.Amplifiers.Amplifier.Values createLibraryAmplifiersAmplifierValues() {
        return new Library.Amplifiers.Amplifier.Values();
    }

    /**
     * Create an instance of {@link Library.LabelRules }
     * 
     */
    public Library.LabelRules createLibraryLabelRules() {
        return new Library.LabelRules();
    }

    /**
     * Create an instance of {@link Library.DrawRules }
     * 
     */
    public Library.DrawRules createLibraryDrawRules() {
        return new Library.DrawRules();
    }

    /**
     * Create an instance of {@link Library.Geometries }
     * 
     */
    public Library.Geometries createLibraryGeometries() {
        return new Library.Geometries();
    }

    /**
     * Create an instance of {@link SymbolSet.LegacySymbols }
     * 
     */
    public SymbolSet.LegacySymbols createSymbolSetLegacySymbols() {
        return new SymbolSet.LegacySymbols();
    }

    /**
     * Create an instance of {@link ModifiersType }
     * 
     */
    public ModifiersType createModifiersType() {
        return new ModifiersType();
    }

    /**
     * Create an instance of {@link SymbolSet.Entities }
     * 
     */
    public SymbolSet.Entities createSymbolSetEntities() {
        return new SymbolSet.Entities();
    }

    /**
     * Create an instance of {@link SymbolSet.Entities.Entity }
     * 
     */
    public SymbolSet.Entities.Entity createSymbolSetEntitiesEntity() {
        return new SymbolSet.Entities.Entity();
    }

    /**
     * Create an instance of {@link SymbolSet.Entities.Entity.EntityTypes }
     * 
     */
    public SymbolSet.Entities.Entity.EntityTypes createSymbolSetEntitiesEntityEntityTypes() {
        return new SymbolSet.Entities.Entity.EntityTypes();
    }

    /**
     * Create an instance of {@link SymbolSet.Entities.Entity.EntityTypes.EntityType }
     * 
     */
    public SymbolSet.Entities.Entity.EntityTypes.EntityType createSymbolSetEntitiesEntityEntityTypesEntityType() {
        return new SymbolSet.Entities.Entity.EntityTypes.EntityType();
    }

    /**
     * Create an instance of {@link nz.co.ctg.jmsfx.generator.schema.EntityType }
     * 
     */
    public nz.co.ctg.jmsfx.generator.schema.EntityType createEntityType() {
        return new nz.co.ctg.jmsfx.generator.schema.EntityType();
    }

    /**
     * Create an instance of {@link DoubleDigitType }
     * 
     */
    public DoubleDigitType createDoubleDigitType() {
        return new DoubleDigitType();
    }

    /**
     * Create an instance of {@link LegacyLetterCodeType }
     * 
     */
    public LegacyLetterCodeType createLegacyLetterCodeType() {
        return new LegacyLetterCodeType();
    }

    /**
     * Create an instance of {@link SymbolSet.SpecialEntitySubTypes }
     * 
     */
    public SymbolSet.SpecialEntitySubTypes createSymbolSetSpecialEntitySubTypes() {
        return new SymbolSet.SpecialEntitySubTypes();
    }

    /**
     * Create an instance of {@link LegacyEntityType }
     * 
     */
    public LegacyEntityType createLegacyEntityType() {
        return new LegacyEntityType();
    }

    /**
     * Create an instance of {@link Tags }
     * 
     */
    public Tags createTags() {
        return new Tags();
    }

    /**
     * Create an instance of {@link EntitySubTypeType }
     * 
     */
    public EntitySubTypeType createEntitySubTypeType() {
        return new EntitySubTypeType();
    }

    /**
     * Create an instance of {@link LegacyFunctionCodeType }
     * 
     */
    public LegacyFunctionCodeType createLegacyFunctionCodeType() {
        return new LegacyFunctionCodeType();
    }

    /**
     * Create an instance of {@link FieldListType.Field }
     * 
     */
    public FieldListType.Field createFieldListTypeField() {
        return new FieldListType.Field();
    }

    /**
     * Create an instance of {@link Library.AmplifierGroups.AmplifierGroup.Amplifiers.Amplifier.Graphics.Graphic }
     * 
     */
    public Library.AmplifierGroups.AmplifierGroup.Amplifiers.Amplifier.Graphics.Graphic createLibraryAmplifierGroupsAmplifierGroupAmplifiersAmplifierGraphicsGraphic() {
        return new Library.AmplifierGroups.AmplifierGroup.Amplifiers.Amplifier.Graphics.Graphic();
    }

    /**
     * Create an instance of {@link Library.HQTFDummies.HQTFDummy.Graphics.Graphic }
     * 
     */
    public Library.HQTFDummies.HQTFDummy.Graphics.Graphic createLibraryHQTFDummiesHQTFDummyGraphicsGraphic() {
        return new Library.HQTFDummies.HQTFDummy.Graphics.Graphic();
    }

    /**
     * Create an instance of {@link Library.Statuses.Status.Graphics.Graphic }
     * 
     */
    public Library.Statuses.Status.Graphics.Graphic createLibraryStatusesStatusGraphicsGraphic() {
        return new Library.Statuses.Status.Graphics.Graphic();
    }

    /**
     * Create an instance of {@link Library.Affiliations.Affiliation.LegacyFrames }
     * 
     */
    public Library.Affiliations.Affiliation.LegacyFrames createLibraryAffiliationsAffiliationLegacyFrames() {
        return new Library.Affiliations.Affiliation.LegacyFrames();
    }

    /**
     * Create an instance of {@link Library.Dimensions.Dimension.SymbolSets.SymbolSetRef }
     * 
     */
    public Library.Dimensions.Dimension.SymbolSets.SymbolSetRef createLibraryDimensionsDimensionSymbolSetsSymbolSetRef() {
        return new Library.Dimensions.Dimension.SymbolSets.SymbolSetRef();
    }

    /**
     * Create an instance of {@link Library.StandardIdentityGroups.StandardIdentityGroup }
     * 
     */
    public Library.StandardIdentityGroups.StandardIdentityGroup createLibraryStandardIdentityGroupsStandardIdentityGroup() {
        return new Library.StandardIdentityGroups.StandardIdentityGroup();
    }

    /**
     * Create an instance of {@link Library.StandardIdentities.StandardIdentity }
     * 
     */
    public Library.StandardIdentities.StandardIdentity createLibraryStandardIdentitiesStandardIdentity() {
        return new Library.StandardIdentities.StandardIdentity();
    }

    /**
     * Create an instance of {@link Library.Contexts.Context }
     * 
     */
    public Library.Contexts.Context createLibraryContextsContext() {
        return new Library.Contexts.Context();
    }

    /**
     * Create an instance of {@link Library.Versions.Version }
     * 
     */
    public Library.Versions.Version createLibraryVersionsVersion() {
        return new Library.Versions.Version();
    }

    /**
     * Create an instance of {@link Library.Amplifiers.Amplifier.Values.Value }
     * 
     */
    public Library.Amplifiers.Amplifier.Values.Value createLibraryAmplifiersAmplifierValuesValue() {
        return new Library.Amplifiers.Amplifier.Values.Value();
    }

    /**
     * Create an instance of {@link Library.LabelRules.LabelRule }
     * 
     */
    public Library.LabelRules.LabelRule createLibraryLabelRulesLabelRule() {
        return new Library.LabelRules.LabelRule();
    }

    /**
     * Create an instance of {@link Library.DrawRules.DrawRule }
     * 
     */
    public Library.DrawRules.DrawRule createLibraryDrawRulesDrawRule() {
        return new Library.DrawRules.DrawRule();
    }

    /**
     * Create an instance of {@link Library.Geometries.Geometry }
     * 
     */
    public Library.Geometries.Geometry createLibraryGeometriesGeometry() {
        return new Library.Geometries.Geometry();
    }

    /**
     * Create an instance of {@link SymbolSet.LegacySymbols.LegacySymbol }
     * 
     */
    public SymbolSet.LegacySymbols.LegacySymbol createSymbolSetLegacySymbolsLegacySymbol() {
        return new SymbolSet.LegacySymbols.LegacySymbol();
    }

    /**
     * Create an instance of {@link ModifiersType.Modifier }
     * 
     */
    public ModifiersType.Modifier createModifiersTypeModifier() {
        return new ModifiersType.Modifier();
    }

    /**
     * Create an instance of {@link SymbolSet.Entities.Entity.EntityTypes.EntityType.EntitySubTypes }
     * 
     */
    public SymbolSet.Entities.Entity.EntityTypes.EntityType.EntitySubTypes createSymbolSetEntitiesEntityEntityTypesEntityTypeEntitySubTypes() {
        return new SymbolSet.Entities.Entity.EntityTypes.EntityType.EntitySubTypes();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LegacyEntityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://disa.mil/JointMilSyML.xsd", name = "LegacyEntity", substitutionHeadNamespace = "http://disa.mil/JointMilSyML.xsd", substitutionHeadName = "Entity")
    public JAXBElement<LegacyEntityType> createLegacyEntity(LegacyEntityType value) {
        return new JAXBElement<LegacyEntityType>(_LegacyEntity_QNAME, LegacyEntityType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link nz.co.ctg.jmsfx.generator.schema.EntityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://disa.mil/JointMilSyML.xsd", name = "Entity")
    public JAXBElement<nz.co.ctg.jmsfx.generator.schema.EntityType> createEntity(nz.co.ctg.jmsfx.generator.schema.EntityType value) {
        return new JAXBElement<nz.co.ctg.jmsfx.generator.schema.EntityType>(_Entity_QNAME, nz.co.ctg.jmsfx.generator.schema.EntityType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://disa.mil/JointMilSyML.xsd", name = "DigitOne", scope = DoubleDigitType.class, defaultValue = "0")
    public JAXBElement<Integer> createDoubleDigitTypeDigitOne(Integer value) {
        return new JAXBElement<Integer>(_DoubleDigitTypeDigitOne_QNAME, Integer.class, DoubleDigitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://disa.mil/JointMilSyML.xsd", name = "DigitTwo", scope = DoubleDigitType.class, defaultValue = "0")
    public JAXBElement<Integer> createDoubleDigitTypeDigitTwo(Integer value) {
        return new JAXBElement<Integer>(_DoubleDigitTypeDigitTwo_QNAME, Integer.class, DoubleDigitType.class, value);
    }

}
