//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 04:45:07 PM NZDT 
//


package nz.co.ctg.jmsfx.generator.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PointLabelMethodType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PointLabelMethodType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="NA"/>
 *     &lt;enumeration value="AroundPoint"/>
 *     &lt;enumeration value="CenteredOnPoint"/>
 *     &lt;enumeration value="NorthOfPoint"/>
 *     &lt;enumeration value="NorthEastOfPoint"/>
 *     &lt;enumeration value="EastOfPoint"/>
 *     &lt;enumeration value="SouthEastOfPoint"/>
 *     &lt;enumeration value="SouthOfPoint"/>
 *     &lt;enumeration value="SouthWestOfPoint"/>
 *     &lt;enumeration value="WestOfPoint"/>
 *     &lt;enumeration value="NorthWestOfPoint"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PointLabelMethodType")
@XmlEnum
public enum PointLabelMethodType {

    NA("NA"),
    @XmlEnumValue("AroundPoint")
    AROUND_POINT("AroundPoint"),
    @XmlEnumValue("CenteredOnPoint")
    CENTERED_ON_POINT("CenteredOnPoint"),
    @XmlEnumValue("NorthOfPoint")
    NORTH_OF_POINT("NorthOfPoint"),
    @XmlEnumValue("NorthEastOfPoint")
    NORTH_EAST_OF_POINT("NorthEastOfPoint"),
    @XmlEnumValue("EastOfPoint")
    EAST_OF_POINT("EastOfPoint"),
    @XmlEnumValue("SouthEastOfPoint")
    SOUTH_EAST_OF_POINT("SouthEastOfPoint"),
    @XmlEnumValue("SouthOfPoint")
    SOUTH_OF_POINT("SouthOfPoint"),
    @XmlEnumValue("SouthWestOfPoint")
    SOUTH_WEST_OF_POINT("SouthWestOfPoint"),
    @XmlEnumValue("WestOfPoint")
    WEST_OF_POINT("WestOfPoint"),
    @XmlEnumValue("NorthWestOfPoint")
    NORTH_WEST_OF_POINT("NorthWestOfPoint");
    private final String value;

    PointLabelMethodType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PointLabelMethodType fromValue(String v) {
        for (PointLabelMethodType c: PointLabelMethodType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
