//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 04:45:07 PM NZDT 
//


package nz.co.ctg.jmsfx.generator.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShapeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ShapeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="NA"/>
 *     &lt;enumeration value="CIRCLE"/>
 *     &lt;enumeration value="CLOVER"/>
 *     &lt;enumeration value="CURVE"/>
 *     &lt;enumeration value="DIAMOND"/>
 *     &lt;enumeration value="RECTANGLE"/>
 *     &lt;enumeration value="SQUARE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ShapeType")
@XmlEnum
public enum ShapeType {

    NA,
    CIRCLE,
    CLOVER,
    CURVE,
    DIAMOND,
    RECTANGLE,
    SQUARE;

    public String value() {
        return name();
    }

    public static ShapeType fromValue(String v) {
        return valueOf(v);
    }

}
