package io.github.ctgnz.jmsfx.hallux.controlmeasure;

import javafx.geometry.Rectangle2D;

import io.github.ctgnz.jmsfx.EntitySubType;
import io.github.ctgnz.jmsfx.EntityType;
import io.github.ctgnz.jmsfx.hallux.IconBounds;
import io.github.ctgnz.jmsfx.types.GraphicType;

public enum ControlMeasureEntitySubType implements EntitySubType {
        FLY_TO_POINT_SONOBUOY("01", "Fly-To-Point (Sonobuoy)", ControlMeasureEntityType.FLY_TO_POINT, GraphicType.FREE_CANVAS),
        FLY_TO_POINT_WEAPON("02", "Fly-To-Point (Weapon)", ControlMeasureEntityType.FLY_TO_POINT, GraphicType.FREE_CANVAS),
        FLY_TO_POINT_NORMAL("03", "Fly-To-Point (Normal)", ControlMeasureEntityType.FLY_TO_POINT, GraphicType.FREE_CANVAS),
        POI_LAUNCH_EVENT("01", "Launch Event (Point of Interest)", ControlMeasureEntityType.POINT_OF_INTEREST, GraphicType.FREE_CANVAS),
        FRIENDLY_AVIATION("01", "Friendly Aviation", ControlMeasureEntityType.DIRECTION_OF_ATTACK, GraphicType.FREE_CANVAS),
        FRIENDLY_MAIN_ATTACK_DECISIVE("02", "Friendly Direction of Main Attack", ControlMeasureEntityType.DIRECTION_OF_ATTACK, GraphicType.FREE_CANVAS),
        FRIENDLY_SUPPORTING_ATTACK("03", "Friendly Direction of Supporting Attack", ControlMeasureEntityType.DIRECTION_OF_ATTACK, GraphicType.FREE_CANVAS),
        FEINT("05", "Feint", ControlMeasureEntityType.DIRECTION_OF_ATTACK, GraphicType.FREE_CANVAS),
        JTAA("01", "Joint Tactical Action Area (JTAA)", ControlMeasureEntityType.ACTION_AREA, GraphicType.FREE_CANVAS),
        SAA("02", "Submarine Action Area (SAA)", ControlMeasureEntityType.ACTION_AREA, GraphicType.FREE_CANVAS),
        SGAA("03", "Submarine-Generated Action Area (SGAA)", ControlMeasureEntityType.ACTION_AREA, GraphicType.FREE_CANVAS),
        PREPARED_BUT_NOT_OCCUPIED("02", "Battle Position - Prepared (P) but not Occupied", ControlMeasureEntityType.BATTLE_POSITION, GraphicType.FREE_CANVAS),
        STRONG_POINT("03", "Strong Point", ControlMeasureEntityType.BATTLE_POSITION, GraphicType.FREE_CANVAS),
        CONTAIN("04", "Contain", ControlMeasureEntityType.BATTLE_POSITION, GraphicType.FREE_CANVAS),
        RETAIN("05", "Retain", ControlMeasureEntityType.BATTLE_POSITION, GraphicType.FREE_CANVAS),
        AXIS_ADVANCE_FRIENDLY_AIRBORNE_AVIATION("01", "Friendly Airborne/Aviation", ControlMeasureEntityType.AXIS_ADVANCE, GraphicType.FREE_CANVAS),
        AXIS_ADVANCE_ATTACK_HELICOPTER("02", "Attack Helicopter", ControlMeasureEntityType.AXIS_ADVANCE, GraphicType.FREE_CANVAS),
        AXIS_ADVANCE_MAIN_ATTACK("03", "Main Attack", ControlMeasureEntityType.AXIS_ADVANCE, GraphicType.FREE_CANVAS),
        AXIS_ADVANCE_SUPPORTING_ATTACK("04", "Supporting Attack", ControlMeasureEntityType.AXIS_ADVANCE, GraphicType.FREE_CANVAS),
        AXIS_ADVANCE_FEINT("06", "Feint", ControlMeasureEntityType.AXIS_ADVANCE, GraphicType.FREE_CANVAS),
        RECONNAISSANCE_OUTPOST("01", "Reconnaissance Outpost", ControlMeasureEntityType.OBSERVATION_POST_OUTPOST_SPECIFIED, GraphicType.FREE_CANVAS),
        FORWARD_OBSERVER_OUTPOST("02", "Forward Observer Outpost", ControlMeasureEntityType.OBSERVATION_POST_OUTPOST_SPECIFIED, GraphicType.FREE_CANVAS),
        CBRN_OBSERVATION_OUTPOST("03", "CBRN Observation Outpost", ControlMeasureEntityType.OBSERVATION_POST_OUTPOST_SPECIFIED, GraphicType.FREE_CANVAS),
        SENSOR_OUTPOST_LISTENING_POST("04", "Sensor Outpost/Listening Post", ControlMeasureEntityType.OBSERVATION_POST_OUTPOST_SPECIFIED, GraphicType.FREE_CANVAS),
        COMBAT_OUTPOST("05", "Combat Outpost", ControlMeasureEntityType.OBSERVATION_POST_OUTPOST_SPECIFIED, GraphicType.FREE_CANVAS),
        LAUNCH_ELLIPSE_CIRCLE("01", "Ellipse/Circle", ControlMeasureEntityType.LAUNCH_AREA, GraphicType.FREE_CANVAS),
        DEFEND_ELLIPSE_CIRCLE("01", "Ellipse/Circle", ControlMeasureEntityType.DEFENDED_AREA, GraphicType.FREE_CANVAS),
        DEFEND_RECTANGLE("02", "Rectangle", ControlMeasureEntityType.DEFENDED_AREA, GraphicType.FREE_CANVAS),
        SHIP_AOI_ELLIPSE_CIRCLE("01", "Ellipse/Circle", ControlMeasureEntityType.SHIP_AREA_OF_INTEREST, GraphicType.FREE_CANVAS),
        SHIP_AOI_RECTANGLE("02", "Rectangle", ControlMeasureEntityType.SHIP_AREA_OF_INTEREST, GraphicType.FREE_CANVAS),
        A("01", "A", ControlMeasureEntityType.HARBOR_ENTRANCE_POINT, GraphicType.FREE_CANVAS),
        Q("02", "Q", ControlMeasureEntityType.HARBOR_ENTRANCE_POINT, GraphicType.FREE_CANVAS),
        X("03", "X", ControlMeasureEntityType.HARBOR_ENTRANCE_POINT, GraphicType.FREE_CANVAS),
        Y("04", "Y", ControlMeasureEntityType.HARBOR_ENTRANCE_POINT, GraphicType.FREE_CANVAS),
        AMBIENT_NOISE("01", "Ambient Noise", ControlMeasureEntityType.SONOBUOY, GraphicType.FREE_CANVAS),
        AIR_TRANSPORTABLE_COMMUNICATION("02", "Air Transportable Communication", ControlMeasureEntityType.SONOBUOY, GraphicType.FREE_CANVAS),
        BARRA("03", "Barra", ControlMeasureEntityType.SONOBUOY, GraphicType.FREE_CANVAS),
        BATHYTHERMOGRAPH_TRANSMITTING("04", "Bathythermograph Transmitting", ControlMeasureEntityType.SONOBUOY, GraphicType.FREE_CANVAS),
        CAMBS("05", "Command Active Multi-Beam (CAMBS)", ControlMeasureEntityType.SONOBUOY, GraphicType.FREE_CANVAS),
        CASS("06", "Command Active Sonobuoy Directional Command Active Sonobuoy System (CASS)", ControlMeasureEntityType.SONOBUOY, GraphicType.FREE_CANVAS),
        DIFAR("07", "Digital Frequency Analysis and Recording (DIFAR)", ControlMeasureEntityType.SONOBUOY, GraphicType.FREE_CANVAS),
        DICASS("08", "Directional Command Active Sonobuoy System (DICASS)", ControlMeasureEntityType.SONOBUOY, GraphicType.FREE_CANVAS),
        ERAPS("09", "Expendable Reliable Acoustic Path Sonobuoy (ERAPS)", ControlMeasureEntityType.SONOBUOY, GraphicType.FREE_CANVAS),
        EXPIRED("10", "Expired", ControlMeasureEntityType.SONOBUOY, GraphicType.FREE_CANVAS),
        KINGPIN("11", "Kingpin", ControlMeasureEntityType.SONOBUOY, GraphicType.FREE_CANVAS),
        LOFAR("12", "Low Frequency Analysis and Recording (LOFAR)", ControlMeasureEntityType.SONOBUOY, GraphicType.FREE_CANVAS),
        PATTERN_CENTER("13", "Pattern Center", ControlMeasureEntityType.SONOBUOY, GraphicType.FREE_CANVAS),
        RANGE_ONLY("14", "Range Only", ControlMeasureEntityType.SONOBUOY, GraphicType.FREE_CANVAS),
        VERTICAL_LINE_ARRAY_DIRECTIONAL_FREQUENCY_ANALYSIS_RECORDING_DIFAR("15", "Vertical Line Array Directional Frequency Analysis and Recording (DIFAR)", ControlMeasureEntityType.SONOBUOY,
                                                                           GraphicType.FREE_CANVAS),
        ELECTRONIC("01", "Electronic", ControlMeasureEntityType.BEARING_LINE, GraphicType.FREE_CANVAS),
        ELECTRONIC_WARFARE_EW("02", "Electronic Warfare (EW)", ControlMeasureEntityType.BEARING_LINE, GraphicType.FREE_CANVAS),
        ACOUSTIC("03", "Acoustic", ControlMeasureEntityType.BEARING_LINE, GraphicType.FREE_CANVAS),
        ACOUSTIC_AMBIGUOUS("04", "Acoustic (Ambiguous)", ControlMeasureEntityType.BEARING_LINE, GraphicType.FREE_CANVAS),
        TORPEDO("05", "Torpedo", ControlMeasureEntityType.BEARING_LINE, GraphicType.FREE_CANVAS),
        ELECTRO_OPTICAL_INTERCEPT("06", "Electro-Optical Intercept", ControlMeasureEntityType.BEARING_LINE, GraphicType.FREE_CANVAS),
        JAMMER("07", "Jammer", ControlMeasureEntityType.BEARING_LINE, GraphicType.FREE_CANVAS),
        RADIO_DIRECTION_FINDER_RDF("08", "Radio Direction Finder (RDF)", ControlMeasureEntityType.BEARING_LINE, GraphicType.FREE_CANVAS),
        ACA_IRREGULAR("01", "Irregular", ControlMeasureEntityType.AIRSPACE_COORDINATION_AREA, GraphicType.FREE_CANVAS),
        ACA_RECTANGULAR("02", "Rectangular", ControlMeasureEntityType.AIRSPACE_COORDINATION_AREA, GraphicType.FREE_CANVAS),
        ACA_CIRCULAR("03", "Circular", ControlMeasureEntityType.AIRSPACE_COORDINATION_AREA, GraphicType.FREE_CANVAS),
        FFA_IRREGULAR("01", "Irregular", ControlMeasureEntityType.FREE_FIRE_AREA, GraphicType.FREE_CANVAS),
        FFA_RECTANGULAR("02", "Rectangular", ControlMeasureEntityType.FREE_FIRE_AREA, GraphicType.FREE_CANVAS),
        FFA_CIRCULAR("03", "Circular", ControlMeasureEntityType.FREE_FIRE_AREA, GraphicType.FREE_CANVAS),
        NFA_IRREGULAR("01", "Irregular", ControlMeasureEntityType.NO_FIRE_AREA, GraphicType.FREE_CANVAS),
        NFA_RECTANGULAR("02", "Rectangular", ControlMeasureEntityType.NO_FIRE_AREA, GraphicType.FREE_CANVAS),
        NFA_CIRCULAR("03", "Circular", ControlMeasureEntityType.NO_FIRE_AREA, GraphicType.FREE_CANVAS),
        RFA_IRREGULAR("01", "Irregular", ControlMeasureEntityType.RESTRICTED_FIRE_AREA, GraphicType.FREE_CANVAS),
        RFA_RECTANGULAR("02", "Rectangular", ControlMeasureEntityType.RESTRICTED_FIRE_AREA, GraphicType.FREE_CANVAS),
        RFA_CIRCULAR("03", "Circular", ControlMeasureEntityType.RESTRICTED_FIRE_AREA, GraphicType.FREE_CANVAS),
        PAA_RECTANGULAR("01", "Rectangular", ControlMeasureEntityType.POSITION_AREA_FOR_ARTILLERY_PAA, GraphicType.FREE_CANVAS),
        PAA_CIRCULAR("02", "Circular", ControlMeasureEntityType.POSITION_AREA_FOR_ARTILLERY_PAA, GraphicType.FREE_CANVAS),
        PAA_IRREGULAR("03", "Irregular", ControlMeasureEntityType.POSITION_AREA_FOR_ARTILLERY_PAA, GraphicType.FREE_CANVAS),
        POINT_SINGLE_TARGET("01", "Point or Single Target", ControlMeasureEntityType.POINT_TARGETS, GraphicType.FREE_CANVAS),
        NUCLEAR_TARGET("02", "Nuclear Target", ControlMeasureEntityType.POINT_TARGETS, GraphicType.FREE_CANVAS),
        TARGET_RECORDED("03", "Target-Recorded", ControlMeasureEntityType.POINT_TARGETS, GraphicType.FREE_CANVAS),
        LINEAR_TARGET("01", "Linear Target", ControlMeasureEntityType.LINEAR_TARGETS, GraphicType.FREE_CANVAS),
        LINEAR_SMOKE_TARGET("02", "Linear Smoke Target", ControlMeasureEntityType.LINEAR_TARGETS, GraphicType.FREE_CANVAS),
        FINAL_PROTECTIVE_FIRE_FPF("03", "Final Protective Fire (FPF)", ControlMeasureEntityType.LINEAR_TARGETS, GraphicType.FREE_CANVAS),
        AREA_TARGET("01", "Area Target", ControlMeasureEntityType.AREA_TARGETS, GraphicType.FREE_CANVAS),
        RECTANGULAR_TARGET("02", "Rectangular Target", ControlMeasureEntityType.AREA_TARGETS, GraphicType.FREE_CANVAS),
        CIRCULAR_TARGET("03", "Circular Target", ControlMeasureEntityType.AREA_TARGETS, GraphicType.FREE_CANVAS),
        RECTANGULAR_TARGET_SINGLE_TARGET("04", "Rectangular Target - Single Target", ControlMeasureEntityType.AREA_TARGETS, GraphicType.FREE_CANVAS),
        SERIES_GROUP_TARGETS("05", "Series of Targets", ControlMeasureEntityType.AREA_TARGETS, GraphicType.FREE_CANVAS),
        SMOKE_TARGET("06", "Smoke Target", ControlMeasureEntityType.AREA_TARGETS, GraphicType.FREE_CANVAS),
        BOMB_AREA("08", "Bomb Area", ControlMeasureEntityType.AREA_TARGETS, GraphicType.FREE_CANVAS),
        FSA_IRREGULAR("01", "Irregular", ControlMeasureEntityType.FIRE_SUPPORT_AREA, GraphicType.FREE_CANVAS),
        FSA_RECTANGULAR("02", "Rectangular", ControlMeasureEntityType.FIRE_SUPPORT_AREA, GraphicType.FREE_CANVAS),
        FSA_CIRCULAR("03", "Circular", ControlMeasureEntityType.FIRE_SUPPORT_AREA, GraphicType.FREE_CANVAS),
        ATI_IRREGULAR("01", "Irregular", ControlMeasureEntityType.ARTILLERY_TARGET_INTELLIGENCE_ZONE, GraphicType.FREE_CANVAS),
        ATI_RECTANGULAR("02", "Rectangular", ControlMeasureEntityType.ARTILLERY_TARGET_INTELLIGENCE_ZONE, GraphicType.FREE_CANVAS),
        ATI_CIRCULAR("03", "Circular", ControlMeasureEntityType.ARTILLERY_TARGET_INTELLIGENCE_ZONE, GraphicType.FREE_CANVAS),
        CFFZ_IRREGULAR("01", "Irregular", ControlMeasureEntityType.CALL_FOR_FIRE_AREA, GraphicType.FREE_CANVAS),
        CFFZ_RECTANGULAR("02", "Rectangular", ControlMeasureEntityType.CALL_FOR_FIRE_AREA, GraphicType.FREE_CANVAS),
        CFFZ_CIRCULAR("03", "Circular", ControlMeasureEntityType.CALL_FOR_FIRE_AREA, GraphicType.FREE_CANVAS),
        CENSOR_IRREGULAR("01", "Irregular", ControlMeasureEntityType.CENSOR_ZONE, GraphicType.FREE_CANVAS),
        CENSOR_RECTANGULAR("02", "Rectangular", ControlMeasureEntityType.CENSOR_ZONE, GraphicType.FREE_CANVAS),
        CENSOR_CIRCULAR("03", "Circular", ControlMeasureEntityType.CENSOR_ZONE, GraphicType.FREE_CANVAS),
        CFZ_IRREGULAR("01", "Irregular", ControlMeasureEntityType.CRITICAL_FRIENDLY_ZONE, GraphicType.FREE_CANVAS),
        CFZ_RECTANGULAR("02", "Rectangular", ControlMeasureEntityType.CRITICAL_FRIENDLY_ZONE, GraphicType.FREE_CANVAS),
        CFZ_CIRCULAR("03", "Circular", ControlMeasureEntityType.CRITICAL_FRIENDLY_ZONE, GraphicType.FREE_CANVAS),
        DA_IRREGULAR("01", "Irregular", ControlMeasureEntityType.DEAD_SPACE_AREA, GraphicType.FREE_CANVAS),
        DA_RECTANGULAR("02", "Rectangular", ControlMeasureEntityType.DEAD_SPACE_AREA, GraphicType.FREE_CANVAS),
        DA_CIRCULAR("03", "Circular", ControlMeasureEntityType.DEAD_SPACE_AREA, GraphicType.FREE_CANVAS),
        TBA_IRREGULAR("01", "Irregular", ControlMeasureEntityType.TARGET_BUILD_UP_AREA, GraphicType.FREE_CANVAS),
        TBA_RECTANGULAR("02", "Rectangular", ControlMeasureEntityType.TARGET_BUILD_UP_AREA, GraphicType.FREE_CANVAS),
        TBA_CIRCULAR("03", "Circular", ControlMeasureEntityType.TARGET_BUILD_UP_AREA, GraphicType.FREE_CANVAS),
        TVAR_IRREGULAR("01", "Irregular", ControlMeasureEntityType.TARGET_VALUE_AREA, GraphicType.FREE_CANVAS),
        TVAR_RECTANGULAR("02", "Rectangular", ControlMeasureEntityType.TARGET_VALUE_AREA, GraphicType.FREE_CANVAS),
        TVAR_CIRCULAR("03", "Circular", ControlMeasureEntityType.TARGET_VALUE_AREA, GraphicType.FREE_CANVAS),
        ZOR_IRREGULAR("01", "Irregular", ControlMeasureEntityType.ZONE_OF_RESPONSIBILITY, GraphicType.FREE_CANVAS),
        ZOR_RECTANGULAR("02", "Rectangular", ControlMeasureEntityType.ZONE_OF_RESPONSIBILITY, GraphicType.FREE_CANVAS),
        ZOR_CIRCULAR("03", "Circular", ControlMeasureEntityType.ZONE_OF_RESPONSIBILITY, GraphicType.FREE_CANVAS),
        BKB_IRREGULAR_BLUE("01", "Irregular-Blue", ControlMeasureEntityType.KILL_BOX, GraphicType.FREE_CANVAS),
        BKB_RECTANGULAR_BLUE("02", "Rectangular-Blue", ControlMeasureEntityType.KILL_BOX, GraphicType.FREE_CANVAS),
        BKB_CIRCULAR_BLUE("03", "Circular-Blue", ControlMeasureEntityType.KILL_BOX, GraphicType.FREE_CANVAS),
        PKB_IRREGULAR_PURPLE("04", "Irregular-Purple", ControlMeasureEntityType.KILL_BOX, GraphicType.FREE_CANVAS),
        PKB_RECTANGULAR_PURPLE("05", "Rectangular-Purple", ControlMeasureEntityType.KILL_BOX, GraphicType.FREE_CANVAS),
        PKB_CIRCULAR_PURPLE("06", "Circular-Purple", ControlMeasureEntityType.KILL_BOX, GraphicType.FREE_CANVAS),
        BLOCK("01", "Block", ControlMeasureEntityType.OBSTACLE_EFFECTS, GraphicType.FREE_CANVAS),
        DISRUPT("02", "Disrupt", ControlMeasureEntityType.OBSTACLE_EFFECTS, GraphicType.FREE_CANVAS),
        FIX("03", "Fix", ControlMeasureEntityType.OBSTACLE_EFFECTS, GraphicType.FREE_CANVAS),
        TURN("04", "Turn", ControlMeasureEntityType.OBSTACLE_EFFECTS, GraphicType.FREE_CANVAS),
        OBSTACLE_BYPASS_EASY("01", "Easy", ControlMeasureEntityType.OBSTACLE_BYPASS, GraphicType.FREE_CANVAS),
        OBSTACLE_BYPASS_DIFFICULT("02", "Difficult", ControlMeasureEntityType.OBSTACLE_BYPASS, GraphicType.FREE_CANVAS),
        OBSTACLE_BYPASS_IMPOSSIBLE("03", "Impossible", ControlMeasureEntityType.OBSTACLE_BYPASS, GraphicType.FREE_CANVAS),
        MINEFIELD_COMPLETED("01", "Completed", ControlMeasureEntityType.MINEFIELD, GraphicType.FREE_CANVAS),
        MINEFIELD_DYNAMIC_DEPICTION("07", "Dynamic Depiction", ControlMeasureEntityType.MINEFIELD, GraphicType.FREE_CANVAS),
        MINED_AREA_FENCED("01", "Mined Area, Fenced", ControlMeasureEntityType.MINED_AREA, GraphicType.FREE_CANVAS),
        PLANNED("01", "Planned", ControlMeasureEntityType.ROADBLOCKS_CRATERS_BLOWN_BRIDGES, GraphicType.FREE_CANVAS),
        EXPLOSIVES_STATE_OF_READINESS_1("02", "Explosives-State of Readiness 1 (Safe)", ControlMeasureEntityType.ROADBLOCKS_CRATERS_BLOWN_BRIDGES, GraphicType.FREE_CANVAS),
        EXPLOSIVES_STATE_OF_READINESS_2("03", "Explosives-State of Readiness 2 (armed but passable)", ControlMeasureEntityType.ROADBLOCKS_CRATERS_BLOWN_BRIDGES, GraphicType.FREE_CANVAS),
        ROADBLOCK_COMPLETE_EXECUTED("04", "Roadblock Complete (Executed)", ControlMeasureEntityType.ROADBLOCKS_CRATERS_BLOWN_BRIDGES, GraphicType.FREE_CANVAS),
        BIO_TOXIC_INDUSTRIAL_MATERIAL("01", "Toxic Industrial Material", ControlMeasureEntityType.BIOLOGICAL_CONTAMINATED_AREA, GraphicType.FREE_CANVAS),
        CHEM_TOXIC_INDUSTRIAL_MATERIAL("01", "Toxic Industrial Material", ControlMeasureEntityType.CHEMICAL_CONTAMINATED_AREA, GraphicType.FREE_CANVAS),
        RAD_TOXIC_INDUSTRIAL_MATERIAL("01", "Toxic Industrial Material", ControlMeasureEntityType.RADIOLOGICAL_CONTAMINATED_AREA, GraphicType.FREE_CANVAS),
        MULTIPLE_STRIKE("01", "Multiple Strike", ControlMeasureEntityType.MINIMUM_SAFE_DISTANCE_ZONE, GraphicType.FREE_CANVAS),
        ANTIPERSONNEL_MINE_WITH_DIRECTIONAL_EFFECTS("01", "Antipersonnel Mine with Directional Effects", ControlMeasureEntityType.ANTIPERSONNEL_MINE, GraphicType.FREE_CANVAS),
        CHEM_TOXIC_INDUSTRIAL_MATERIAL_POINT("01", "Toxic Industrial Material", ControlMeasureEntityType.CHEMICAL_EVENT, GraphicType.FREE_CANVAS),
        BIO_TOXIC_INDUSTRIAL_MATERIAL_POINT("01", "Toxic Industrial Material", ControlMeasureEntityType.BIOLOGICAL_EVENT, GraphicType.FREE_CANVAS),
        RAD_TOXIC_INDUSTRIAL_MATERIAL_POINT("01", "Toxic Industrial Material", ControlMeasureEntityType.RADIOLOGICAL, GraphicType.FREE_CANVAS),
        DECON_ALTERNATE("01", "Alternate", ControlMeasureEntityType.GENERAL_DECONTAMINATION_POINT_SITE, GraphicType.FREE_CANVAS),
        DECON_EQUIPMENT("02", "Equipment", ControlMeasureEntityType.GENERAL_DECONTAMINATION_POINT_SITE, GraphicType.FREE_CANVAS),
        DECON_TROOP("03", "Troop", ControlMeasureEntityType.GENERAL_DECONTAMINATION_POINT_SITE, GraphicType.FREE_CANVAS),
        DECON_EQUIPMENT_TROOP("04", "Equipment/Troop", ControlMeasureEntityType.GENERAL_DECONTAMINATION_POINT_SITE, GraphicType.FREE_CANVAS),
        DECON_OPERATIONAL("05", "Operational", ControlMeasureEntityType.GENERAL_DECONTAMINATION_POINT_SITE, GraphicType.FREE_CANVAS),
        DECON_THOROUGH("06", "Thorough", ControlMeasureEntityType.GENERAL_DECONTAMINATION_POINT_SITE, GraphicType.FREE_CANVAS),
        DECON_MAIN_EQUIPMENT("07", "Main Equipment", ControlMeasureEntityType.GENERAL_DECONTAMINATION_POINT_SITE, GraphicType.FREE_CANVAS),
        DECON_FORWARD_TROOP("08", "Forward Troop", ControlMeasureEntityType.GENERAL_DECONTAMINATION_POINT_SITE, GraphicType.FREE_CANVAS),
        DECON_WOUNDED_PERSONNEL("09", "Wounded Personnel", ControlMeasureEntityType.GENERAL_DECONTAMINATION_POINT_SITE, GraphicType.FREE_CANVAS),
        FIXED_PREFABRICATED("01", "Fixed and Prefabricated", ControlMeasureEntityType.OTHER_SIMILAR_OBSTACLES, GraphicType.FREE_CANVAS),
        MOVABLE("02", "Movable", ControlMeasureEntityType.OTHER_SIMILAR_OBSTACLES, GraphicType.FREE_CANVAS),
        MOVABLE_PREFABRICATED("03", "Movable and Prefabricated", ControlMeasureEntityType.OTHER_SIMILAR_OBSTACLES, GraphicType.FREE_CANVAS),
        TOWER_LOW("01", "Tower-Low", ControlMeasureEntityType.VERTICAL_OBSTRUCTIONS, GraphicType.FREE_CANVAS),
        TOWER_HIGH("02", "Tower-High", ControlMeasureEntityType.VERTICAL_OBSTRUCTIONS, GraphicType.FREE_CANVAS),
        OVERHEAD_WIRE("03", "Overhead Wire", ControlMeasureEntityType.VERTICAL_OBSTRUCTIONS, GraphicType.FREE_CANVAS),
        MINE_LINE("01", "Mineline", ControlMeasureEntityType.OBSTACLE_LINE, GraphicType.FREE_CANVAS),
        AT_UNDER_CONSTRUCTION("01", "Under Construction", ControlMeasureEntityType.ANTITANK_OBSTACLES, GraphicType.FREE_CANVAS),
        AT_COMPLETED("02", "Completed", ControlMeasureEntityType.ANTITANK_OBSTACLES, GraphicType.FREE_CANVAS),
        AT_REINFORCED_WITH_MINES("03", "Reinforced-with Antitank Mines", ControlMeasureEntityType.ANTITANK_OBSTACLES, GraphicType.FREE_CANVAS),
        AT_ANTITANK_WALL("04", "Antitank Wall", ControlMeasureEntityType.ANTITANK_OBSTACLES, GraphicType.FREE_CANVAS),
        UNSPECIFIED_WIRE("01", "Unspecified Wire", ControlMeasureEntityType.WIRE_OBSTACLES, GraphicType.FREE_CANVAS),
        SINGLE_FENCE_WIRE("02", "Single Fence Wire", ControlMeasureEntityType.WIRE_OBSTACLES, GraphicType.FREE_CANVAS),
        DOUBLE_FENCE_WIRE("03", "Double Fence Wire", ControlMeasureEntityType.WIRE_OBSTACLES, GraphicType.FREE_CANVAS),
        DOUBLE_APRON_FENCE("04", "Double Apron Fence", ControlMeasureEntityType.WIRE_OBSTACLES, GraphicType.FREE_CANVAS),
        LOW_WIRE_FENCE("05", "Low Wire Fence", ControlMeasureEntityType.WIRE_OBSTACLES, GraphicType.FREE_CANVAS),
        HIGH_WIRE_FENCE("06", "High Wire Fence", ControlMeasureEntityType.WIRE_OBSTACLES, GraphicType.FREE_CANVAS),
        SINGLE_CONCERTINA("07", "Single Concertina", ControlMeasureEntityType.WIRE_OBSTACLES, GraphicType.FREE_CANVAS),
        DOUBLE_STRAND_CONCERTINA("08", "Double Strand Concertina", ControlMeasureEntityType.WIRE_OBSTACLES, GraphicType.FREE_CANVAS),
        TRIPLE_STRAND_CONCERTINA("09", "Triple Strand Concertina", ControlMeasureEntityType.WIRE_OBSTACLES, GraphicType.FREE_CANVAS),
        AMBULANCE_EXCHANGE_POINT("01", "Ambulance Exchange Point", ControlMeasureEntityType.AMBULANCE_POINTS, GraphicType.FREE_CANVAS),
        AMBULANCE_CONTROL_POINT("02", "Ambulance Control Point", ControlMeasureEntityType.AMBULANCE_POINTS, GraphicType.FREE_CANVAS),
        AMBULANCE_LOAD_POINT("03", "Ambulance Load Point", ControlMeasureEntityType.AMBULANCE_POINTS, GraphicType.FREE_CANVAS),
        AMBULANCE_RELAY_POINT("04", "Ambulance Relay Point", ControlMeasureEntityType.AMBULANCE_POINTS, GraphicType.FREE_CANVAS),
        NATO_CLASS_1_SUPPLY_POINT("01", "NATO Class I Supply Point", ControlMeasureEntityType.GENERAL_SUPPLY_POINT, GraphicType.FREE_CANVAS),
        NATO_CLASS_2_SUPPLY_POINT("02", "NATO Class II Supply Point", ControlMeasureEntityType.GENERAL_SUPPLY_POINT, GraphicType.FREE_CANVAS),
        NATO_CLASS_3_SUPPLY_POINT("03", "NATO Class III Supply Point", ControlMeasureEntityType.GENERAL_SUPPLY_POINT, GraphicType.FREE_CANVAS),
        NATO_CLASS_4_SUPPLY_POINT("04", "NATO Class IV Supply Point", ControlMeasureEntityType.GENERAL_SUPPLY_POINT, GraphicType.FREE_CANVAS),
        NATO_CLASS_5_SUPPLY_POINT("05", "NATO Class V Supply Point", ControlMeasureEntityType.GENERAL_SUPPLY_POINT, GraphicType.FREE_CANVAS),
        NATO_MULTIPLE_CLASS_SUPPLY_POINT("06", "NATO Multiple Class Supply Point", ControlMeasureEntityType.GENERAL_SUPPLY_POINT, GraphicType.FREE_CANVAS),
        US_CLASS_01_SUPPLY_POINT("07", "US Class I Supply Point", ControlMeasureEntityType.GENERAL_SUPPLY_POINT, GraphicType.FREE_CANVAS),
        US_CLASS_02_SUPPLY_POINT("08", "US Class II Supply Point", ControlMeasureEntityType.GENERAL_SUPPLY_POINT, GraphicType.FREE_CANVAS),
        US_CLASS_03_SUPPLY_POINT("09", "US Class III Supply Point", ControlMeasureEntityType.GENERAL_SUPPLY_POINT, GraphicType.FREE_CANVAS),
        US_CLASS_04_SUPPLY_POINT("10", "US Class IV Supply Point", ControlMeasureEntityType.GENERAL_SUPPLY_POINT, GraphicType.FREE_CANVAS),
        US_CLASS_05_SUPPLY_POINT("11", "US Class V Supply Point", ControlMeasureEntityType.GENERAL_SUPPLY_POINT, GraphicType.FREE_CANVAS),
        US_CLASS_06_SUPPLY_POINT("12", "US Class VI Supply Point", ControlMeasureEntityType.GENERAL_SUPPLY_POINT, GraphicType.FREE_CANVAS),
        US_CLASS_07_SUPPLY_POINT("13", "US Class VII Supply Point", ControlMeasureEntityType.GENERAL_SUPPLY_POINT, GraphicType.FREE_CANVAS),
        US_CLASS_08_SUPPLY_POINT("14", "US Class VIII Supply Point", ControlMeasureEntityType.GENERAL_SUPPLY_POINT, GraphicType.FREE_CANVAS),
        US_CLASS_09_SUPPLY_POINT("15", "US Class IX Supply Point", ControlMeasureEntityType.GENERAL_SUPPLY_POINT, GraphicType.FREE_CANVAS),
        US_CLASS_10_SUPPLY_POINT("16", "US Class X Supply Point", ControlMeasureEntityType.GENERAL_SUPPLY_POINT, GraphicType.FREE_CANVAS),
        MSR_ONE_WAY_TRAFFIC("01", "One Way Traffic", ControlMeasureEntityType.MAIN_SUPPLY_ROUTE, GraphicType.FREE_CANVAS),
        MSR_TWO_WAY_TRAFFIC("02", "Two Way Traffic", ControlMeasureEntityType.MAIN_SUPPLY_ROUTE, GraphicType.FREE_CANVAS),
        MSR_ALTERNATING_TRAFFIC("03", "Alternating Traffic", ControlMeasureEntityType.MAIN_SUPPLY_ROUTE, GraphicType.FREE_CANVAS),
        ASR_ONE_WAY_TRAFFIC("01", "One Way Traffic", ControlMeasureEntityType.ALTERNATE_SUPPLY_ROUTE, GraphicType.FREE_CANVAS),
        ASR_TWO_WAY_TRAFFIC("02", "Two Way Traffic", ControlMeasureEntityType.ALTERNATE_SUPPLY_ROUTE, GraphicType.FREE_CANVAS),
        ASR_ALTERNATING_TRAFFIC("03", "Alternating Traffic", ControlMeasureEntityType.ALTERNATE_SUPPLY_ROUTE, GraphicType.FREE_CANVAS),
        ROUTE_ONE_WAY_TRAFFIC("01", "One Way Traffic", ControlMeasureEntityType.ROUTE, GraphicType.FREE_CANVAS),
        ROUTE_ALTERNATING_TRAFFIC("02", "Alternating Traffic", ControlMeasureEntityType.ROUTE, GraphicType.FREE_CANVAS),
        TMT_COVER("01", "Cover", ControlMeasureEntityType.SECURITY, GraphicType.FREE_CANVAS),
        TMT_GUARD("02", "Guard", ControlMeasureEntityType.SECURITY, GraphicType.FREE_CANVAS),
        TMT_SCREEN("03", "Screen", ControlMeasureEntityType.SECURITY, GraphicType.FREE_CANVAS),
        HMSD_SMALL("01", "Human Made Space Debris, Small", ControlMeasureEntityType.HUMAN_MADE_SPACE_DEBRIS, GraphicType.FREE_CANVAS),
        HMSD_MEDIUM("02", "Human Made Space Debris, Medium", ControlMeasureEntityType.HUMAN_MADE_SPACE_DEBRIS, GraphicType.FREE_CANVAS),
        HMSD_BIG("03", "Human Made Space Debris, Big", ControlMeasureEntityType.HUMAN_MADE_SPACE_DEBRIS, GraphicType.FREE_CANVAS),
        NSD_SMALL("01", "Natural Space Debris, Small", ControlMeasureEntityType.NATURAL_SPACE_DEBRIS, GraphicType.FREE_CANVAS),
        NSD_MEDIUM("02", "Natural Space Debris, Medium", ControlMeasureEntityType.NATURAL_SPACE_DEBRIS, GraphicType.FREE_CANVAS),
        NSD_BIG("03", "Natural Space Debris, Big", ControlMeasureEntityType.NATURAL_SPACE_DEBRIS, GraphicType.FREE_CANVAS);

    private final String id;
    private final String label;
    private final ControlMeasureEntityType entityType;
    private final GraphicType graphicType;

    ControlMeasureEntitySubType(String id, String label, ControlMeasureEntityType entityType, GraphicType graphicType) {
        this.id = id;
        this.label = label;
        this.entityType = entityType;
        this.graphicType = graphicType;
    }

    @Override
    public GraphicType getGraphicType() {
        return graphicType;
    }

    @Override
    public Rectangle2D getIconBounds() {
        return IconBounds.lookup(getGraphicIdentifier(), getGraphicType());
    }

    @Override
    public String getId() {
        return id;
    }

    @Override
    public String getLabel() {
        return label;
    }

    @Override
    public EntityType getEntityType() {
        return entityType;
    }

}