package ${iconPackage};

import java.util.Map;

import javafx.geometry.Rectangle2D;

import ${basePackage}.IconGeometry;

/**
 * Bounds for the sector modifier fragments that draw outside the bounding octagon.
 * <p>
 * APP-6E places sector modifiers within the octagon, and all but a handful do, so {@link IconGeometry#OCTAGON} serves as their bounds without measuring each one. The exceptions
 * are genuine rather than drawing errors - the Land Units supply bar and headquarters rule are full-width horizontal rules, for instance - so they carry measured bounds here.
 * <p>
 * Generated by {@code FragmentMeasurer}; do not edit. Keyed by graphic identifier, which is the fragment's file stem.
 */
public final class ModifierBounds {

    private static final Map<String, Rectangle2D> BOUNDS = Map.ofEntries(
<#list modifierBounds as identifier, rect>
        Map.entry("${identifier}", new Rectangle2D(${rect.minX?c}, ${rect.minY?c}, ${rect.width?c}, ${rect.height?c}))<#sep>,
</#list>);

    /**
     * The bounds of the fragment with this identifier, or {@link IconGeometry#OCTAGON} when it keeps within the octagon like the great majority.
     */
    public static Rectangle2D lookup(String graphicIdentifier) {
        return BOUNDS.getOrDefault(graphicIdentifier, IconGeometry.OCTAGON);
    }

    private ModifierBounds() {
    }

}
