<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <name>JMSFX Model</name>
    <artifactId>jmsfx-editor</artifactId>
    <packaging>jar</packaging>

    <parent>
        <groupId>io.github.ctgnz</groupId>
        <artifactId>jmsfx</artifactId>
        <version>1.1.8-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>        
    </parent>

    <dependencies>
        <dependency>
            <groupId>io.github.ctgnz</groupId>
            <artifactId>jmsfx-core</artifactId>
            <version>1.1.8-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.github.ctgnz</groupId>
            <artifactId>jmsfx-standard</artifactId>
            <version>1.1.8-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
            <version>2.2</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-all</artifactId>
            <version>2.0.2-beta</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>src/main/java</sourceDirectory>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <configuration>
                    <excludePackageNames>nz.co.ctg.jmsfx.model</excludePackageNames>
                    <subpackages>nz.co.ctg.jmsfx.icon</subpackages>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>