package io.github.ctgnz.jmsfx.generator;

import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.stream.Stream;

import javax.xml.XMLConstants;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import org.w3c.dom.Attr;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NamedNodeMap;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import io.github.ctgnz.jmsfx.generator.yaml.JmsfxParser;

/**
 * Compares the SVG fragments of two models - jmsfx-standard and hallux's jmsfx-hallux - and reports how they differ.
 * <p>
 * The two trees are meant to relate by whole files being added or removed: hallux extends the base set, and renames a few where its own numbering differs. Anything present in both
 * should draw the same thing. This exists so that holds after a round of fragment edits, since those have to be carried across by hand.
 * <p>
 * Editor noise is deliberately ignored. Inkscape rewrites element ids and adds its own metadata on every save, and re-serialises coordinates, so {@code 303.52} comes back as
 * {@code 303.51999} and {@code 40,20} as {@code 40, 20}. Comparing bytes reports dozens of differences that draw identically; this compares the drawable content instead.
 * <p>
 * Reports only - nothing is copied or written. Run it with the two config files:
 *
 * <pre>
 * java io.github.ctgnz.jmsfx.generator.FragmentComparator [/config.yml] [/config-hallux.yml]
 * </pre>
 */
public class FragmentComparator {

    /** Coordinates are compared to this many decimals, which is well below anything visible and absorbs re-serialisation drift. */
    private static final int PRECISION = 3;

    private static final String INKSCAPE_NS = "http://www.inkscape.org/namespaces/inkscape";
    private static final String SODIPODI_NS = "http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd";

    /** Regenerated by the editor on every save, so it says nothing about what is drawn. */
    private static final String ID_ATTRIBUTE = "id";

    public static void main(String[] args) {
        String left = args.length > 0 ? args[0] : "/config.yml";
        String right = args.length > 1 ? args[1] : "/config-hallux.yml";
        try {
            new FragmentComparator().compare(left, right);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private final JmsfxParser parser = new JmsfxParser();

    public void compare(String leftConfig, String rightConfig) throws Exception {
        Path left = svgRoot(leftConfig);
        Path right = svgRoot(rightConfig);
        System.out.format("left  %s%n", left);
        System.out.format("right %s%n%n", right);

        Map<String, Path> leftFiles = index(left);
        Map<String, Path> rightFiles = index(right);

        List<String> onlyLeft = new ArrayList<>();
        List<String> onlyRight = new ArrayList<>();
        List<String> differing = new ArrayList<>();
        List<String> unreadable = new ArrayList<>();
        int identical = 0;

        TreeSet<String> all = new TreeSet<>(leftFiles.keySet());
        all.addAll(rightFiles.keySet());
        for (String name : all) {
            Path a = leftFiles.get(name);
            Path b = rightFiles.get(name);
            if (b == null) {
                onlyLeft.add(name);
                continue;
            }
            if (a == null) {
                onlyRight.add(name);
                continue;
            }
            String left1 = fingerprint(a);
            String right1 = fingerprint(b);
            if (left1 == null || right1 == null) {
                unreadable.add(name + (left1 == null ? "  (left unreadable)" : "  (right unreadable)"));
            } else if (left1.equals(right1)) {
                identical++;
            } else {
                differing.add(name);
            }
        }

        System.out.format("shared and identical : %d%n", identical);
        System.out.format("only on the left     : %d%n", onlyLeft.size());
        System.out.format("only on the right    : %d%n", onlyRight.size());
        System.out.format("shared but differing : %d%n", differing.size());
        System.out.format("unreadable           : %d%n", unreadable.size());

        report("Only on the left", onlyLeft);
        report("Only on the right", onlyRight);
        report("Shared but drawing differently - these need reconciling", differing);
        report("Could not be parsed", unreadable);
    }

    private static void report(String heading, List<String> names) {
        if (names.isEmpty()) {
            return;
        }
        System.out.format("%n%s (%d):%n", heading, names.size());
        names.forEach(name -> System.out.format("   %s%n", name));
    }

    /**
     * Everything the file draws, in document order, with the editor's own additions stripped out - its namespaces, the ids it regenerates, and the precision it re-serialises
     * coordinates at. Two files with the same fingerprint draw the same thing.
     */
    private String fingerprint(Path file) {
        try (InputStream in = Files.newInputStream(file)) {
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            factory.setNamespaceAware(true);
            // Some fragments declare a DOCTYPE pointing at svg11.dtd over http. Nothing here needs
            // it, and fetching it would make the comparison depend on a network round trip, so skip
            // loading it rather than refusing the document.
            factory.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
            factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, "");
            factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_SCHEMA, "");
            DocumentBuilder builder = factory.newDocumentBuilder();
            Document document = builder.parse(in);
            StringBuilder out = new StringBuilder();
            append(document.getDocumentElement(), out);
            return out.toString();
        } catch (Exception e) {
            return null;
        }
    }

    private void append(Node node, StringBuilder out) {
        if (node.getNodeType() != Node.ELEMENT_NODE || isEditorMetadata(node)) {
            return;
        }
        Element element = (Element) node;
        out.append('<')
            .append(element.getLocalName());
        NamedNodeMap attributes = element.getAttributes();
        Map<String, String> sorted = new TreeMap<>();
        for (int i = 0; i < attributes.getLength(); i++) {
            Attr attribute = (Attr) attributes.item(i);
            if (isEditorMetadata(attribute) || ID_ATTRIBUTE.equals(attribute.getLocalName())) {
                continue;
            }
            sorted.put(attribute.getLocalName(), normalise(attribute.getValue()));
        }
        sorted.forEach((name, value) -> out.append(' ')
            .append(name)
            .append('=')
            .append(value));
        out.append('>');
        NodeList children = element.getChildNodes();
        for (int i = 0; i < children.getLength(); i++) {
            append(children.item(i), out);
        }
    }

    private Map<String, Path> index(Path root) throws Exception {
        Map<String, Path> files = new TreeMap<>();
        try (Stream<Path> tree = Files.walk(root)) {
            tree.filter(Files::isRegularFile)
                .filter(path -> path.getFileName()
                    .toString()
                    .endsWith(".svg"))
                .forEach(path -> files.put(root.relativize(path)
                    .toString()
                    .replace('\\', '/'), path));
        }
        return files;
    }

    private boolean isEditorMetadata(Node node) {
        String namespace = node.getNamespaceURI();
        return INKSCAPE_NS.equals(namespace) || SODIPODI_NS.equals(namespace) || XMLConstants.XMLNS_ATTRIBUTE_NS_URI.equals(namespace);
    }

    /** Collapses whitespace and rounds every number, so re-serialisation drift and reformatted lists compare equal. */
    private String normalise(String value) {
        String collapsed = value.trim()
            .replaceAll("\\s+", " ");
        StringBuilder out = new StringBuilder(collapsed.length());
        int i = 0;
        while (i < collapsed.length()) {
            int start = i;
            while (i < collapsed.length() && (Character.isDigit(collapsed.charAt(i)) || collapsed.charAt(i) == '.'
                                              || (collapsed.charAt(i) == '-' && i == start))) {
                i++;
            }
            if (i > start) {
                String token = collapsed.substring(start, i);
                try {
                    out.append(String.format(Locale.ROOT, "%." + PRECISION + "f", Double.parseDouble(token)));
                } catch (NumberFormatException e) {
                    out.append(token);
                }
            } else {
                out.append(collapsed.charAt(i));
                i++;
            }
        }
        return out.toString();
    }

    private Path svgRoot(String configFile) throws Exception {
        try (InputStream in = FragmentComparator.class.getResourceAsStream(configFile)) {
            if (in == null) {
                throw new IllegalArgumentException("no such config on the classpath: " + configFile);
            }
            GeneratorConfig config = parser.readConfig(in);
            if (config.getResourceDir() == null) {
                throw new IllegalStateException(configFile + " has no resourceDir, so its fragments cannot be found");
            }
            return config.getResourceDir()
                .resolve("svg");
        }
    }

}
