package io.github.ctgnz.jmsfx.generator;

import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;

import javax.xml.XMLConstants;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import org.w3c.dom.Attr;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NamedNodeMap;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 * Everything an SVG fragment draws, reduced to a single string. Two fragments with the same fingerprint draw the same thing.
 * <p>
 * The editor's own contributions are deliberately excluded, because they say nothing about the drawing: Inkscape's namespaces and the elements in them, the ids it regenerates on
 * every save, and the precision it re-serialises coordinates at ({@code 303.52} comes back as {@code 303.51999}, {@code 40,20} as {@code 40, 20}). Comparing bytes reports dozens
 * of differences that draw identically; this compares the drawable content instead.
 * <p>
 * Text content <em>is</em> included. It was not, when this was private to {@link FragmentComparator} and only ever asked whether two trees agreed - but as the invariant that
 * {@link FragmentNormaliser} rewrites a file without changing it, a fingerprint blind to text would not notice a normaliser that dropped the {@code ?} out of an {@code <text>}
 * element, which is precisely the kind of content jmsfx#53 and jmsfx#62 were about.
 */
public final class SvgFingerprint {

    /** Coordinates are compared to this many decimals, which is well below anything visible and absorbs re-serialisation drift. */
    private static final int PRECISION = 3;

    private static final String INKSCAPE_NS = "http://www.inkscape.org/namespaces/inkscape";
    private static final String SODIPODI_NS = "http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd";

    /** Regenerated by the editor on every save, so it says nothing about what is drawn - and {@link FragmentNormaliser} drops the unreferenced ones outright. */
    private static final String ID_ATTRIBUTE = "id";

    private static final String DEFS_ELEMENT = "defs";

    /**
     * Parses a fragment, with external entity resolution turned off.
     * <p>
     * Some fragments declare a DOCTYPE pointing at svg11.dtd over http. Nothing here needs it, and fetching it would make this depend on a network round trip, so the DTD is
     * skipped rather than the document refused.
     */
    public static Document parse(InputStream in) throws Exception {
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        factory.setNamespaceAware(true);
        factory.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
        factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, "");
        factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_SCHEMA, "");
        DocumentBuilder builder = factory.newDocumentBuilder();
        return builder.parse(in);
    }

    /** The fingerprint of a file, or {@code null} if it cannot be parsed. */
    public static String of(Path file) {
        try (InputStream in = Files.newInputStream(file)) {
            return of(parse(in));
        } catch (Exception e) {
            return null;
        }
    }

    public static String of(Document document) {
        StringBuilder out = new StringBuilder();
        append(document.getDocumentElement(), out, true);
        return out.toString();
    }

    /**
     * As {@link #of(Document)}, but with every number left exactly as written.
     * <p>
     * Rounding to {@link #PRECISION} is the right way to compare two independently-edited trees, where the question is only whether they agree. It is the wrong way to check a
     * rewrite that deliberately adjusts numbers, because a value sitting on a rounding boundary flips sides for a change far smaller than the rounding itself: {@code 43.86149}
     * written as {@code 43.8615} has moved by 1e-5, but rounds to {@code 43.861} before and {@code 43.862} after. Twenty-six fragments were refused for exactly that, none of them
     * for a real difference.
     * <p>
     * Pair this with {@link #equivalent(String, String, double)}, which compares the numbers numerically against a stated tolerance and everything else literally - a stronger
     * check than the rounded string, since it bounds how far any single value may have moved instead of quantising them all first.
     */
    public static String exact(Document document) {
        StringBuilder out = new StringBuilder();
        append(document.getDocumentElement(), out, false);
        return out.toString();
    }

    /**
     * Whether two exact fingerprints describe the same drawing, allowing each number to differ by at most {@code tolerance}.
     * <p>
     * Everything that is not a number has to match character for character, so an element, an attribute or a piece of text that appeared, vanished or changed is still caught - as
     * is a coordinate separator lost, since that turns two numbers into one and the two sides stop lining up.
     */
    public static boolean equivalent(String left, String right, double tolerance) {
        int i = 0;
        int j = 0;
        while (i < left.length() && j < right.length()) {
            int leftEnd = numberEnd(left, i);
            int rightEnd = numberEnd(right, j);
            if (leftEnd > i && rightEnd > j) {
                double a = Double.parseDouble(left.substring(i, leftEnd));
                double b = Double.parseDouble(right.substring(j, rightEnd));
                if (Math.abs(a - b) > tolerance) {
                    return false;
                }
                i = leftEnd;
                j = rightEnd;
            } else if (left.charAt(i) == right.charAt(j)) {
                i++;
                j++;
            } else {
                return false;
            }
        }
        return i == left.length() && j == right.length();
    }

    /** The end of the number starting at {@code from}, or {@code from} itself if there is not one there. */
    private static int numberEnd(String value, int from) {
        int i = from;
        if (i < value.length() && value.charAt(i) == '-') {
            i++;
        }
        int digits = i;
        while (i < value.length() && (Character.isDigit(value.charAt(i)) || value.charAt(i) == '.')) {
            i++;
        }
        if (i == digits) {
            return from;
        }
        try {
            Double.parseDouble(value.substring(from, i));
            return i;
        } catch (NumberFormatException e) {
            return from;
        }
    }

    /** Whether a node is the editor's own, rather than part of the drawing. */
    public static boolean isEditorMetadata(Node node) {
        String namespace = node.getNamespaceURI();
        if (INKSCAPE_NS.equals(namespace) || SODIPODI_NS.equals(namespace)) {
            return true;
        }
        // A namespace declaration is not itself drawable, so it stays out of the fingerprint - but only the
        // editor's own are safe to delete from the file. Dropping xmlns="http://www.w3.org/2000/svg" would
        // leave something that is no longer SVG at all, so that distinction lives here rather than in the
        // caller, where it was once got wrong.
        return XMLConstants.XMLNS_ATTRIBUTE_NS_URI.equals(namespace);
    }

    /** A namespace declaration that exists only because the editor touched the file, and can be deleted with it. */
    public static boolean isEditorNamespaceDeclaration(Node node) {
        if (!XMLConstants.XMLNS_ATTRIBUTE_NS_URI.equals(node.getNamespaceURI())) {
            return false;
        }
        String declared = node.getNodeValue();
        return INKSCAPE_NS.equals(declared) || SODIPODI_NS.equals(declared);
    }

    /**
     * An empty {@code <defs/>}, which Inkscape leaves behind on every save.
     * <p>
     * It contributes nothing to the drawing - a {@code <defs>} is never rendered directly at all, only referenced - so it is excluded from the fingerprint, which lets
     * {@link FragmentNormaliser} drop it without tripping its own invariant. One holding actual definitions is real content and is kept, since what it holds can be referenced.
     */
    public static boolean isEmptyDefs(Node node) {
        if (node.getNodeType() != Node.ELEMENT_NODE || !DEFS_ELEMENT.equals(node.getLocalName())) {
            return false;
        }
        NodeList children = node.getChildNodes();
        for (int i = 0; i < children.getLength(); i++) {
            Node child = children.item(i);
            if (child.getNodeType() == Node.ELEMENT_NODE && !isEditorMetadata(child)) {
                return false;
            }
        }
        return true;
    }

    private static void append(Node node, StringBuilder out, boolean round) {
        if (node.getNodeType() == Node.TEXT_NODE || node.getNodeType() == Node.CDATA_SECTION_NODE) {
            String text = node.getNodeValue()
                .trim()
                .replaceAll("\\s+", " ");
            if (!text.isEmpty()) {
                out.append('"')
                    .append(text)
                    .append('"');
            }
            return;
        }
        if (node.getNodeType() != Node.ELEMENT_NODE || isEditorMetadata(node) || isEmptyDefs(node)) {
            return;
        }
        Element element = (Element) node;
        // The namespace, not just the name: an element's namespace is what makes it SVG, and it is carried by
        // a declaration the fingerprint otherwise ignores. Without this, deleting xmlns="http://www.w3.org/2000/svg"
        // leaves every element's local name unchanged and the fingerprint none the wiser.
        out.append('<')
            .append(element.getNamespaceURI())
            .append(':')
            .append(element.getLocalName());
        NamedNodeMap attributes = element.getAttributes();
        Map<String, String> sorted = new TreeMap<>();
        for (int i = 0; i < attributes.getLength(); i++) {
            Attr attribute = (Attr) attributes.item(i);
            if (isEditorMetadata(attribute) || ID_ATTRIBUTE.equals(attribute.getLocalName())) {
                continue;
            }
            sorted.put(attribute.getLocalName(), normalise(attribute.getValue(), round));
        }
        sorted.forEach((name, value) -> out.append(' ')
            .append(name)
            .append('=')
            .append(value));
        out.append('>');
        NodeList children = element.getChildNodes();
        for (int i = 0; i < children.getLength(); i++) {
            append(children.item(i), out, round);
        }
    }

    /** Collapses whitespace and, when {@code round} is set, rounds every number, so re-serialisation drift and reformatted lists compare equal. */
    private static String normalise(String value, boolean round) {
        String collapsed = value.trim()
            .replaceAll("\\s+", " ");
        StringBuilder out = new StringBuilder(collapsed.length());
        int i = 0;
        while (i < collapsed.length()) {
            int start = i;
            while (i < collapsed.length() && (Character.isDigit(collapsed.charAt(i)) || collapsed.charAt(i) == '.'
                                              || (collapsed.charAt(i) == '-' && i == start))) {
                i++;
            }
            if (i > start) {
                String token = collapsed.substring(start, i);
                try {
                    out.append(round ? String.format(Locale.ROOT, "%." + PRECISION + "f", Double.parseDouble(token)) : token);
                } catch (NumberFormatException e) {
                    out.append(token);
                }
            } else {
                out.append(collapsed.charAt(i));
                i++;
            }
        }
        return out.toString();
    }

    private SvgFingerprint() {
    }

}
