package io.github.ctgnz.jmsfx.standard;

import java.util.Map;

import javafx.geometry.Rectangle2D;

import io.github.ctgnz.jmsfx.IconGeometry;

/**
 * Bounds for the sector modifier fragments that draw outside the bounding octagon.
 * <p>
 * APP-6E places sector modifiers within the octagon, and all but a handful do, so {@link IconGeometry#OCTAGON} serves as their bounds without measuring each one. The exceptions
 * are genuine rather than drawing errors - the Land Units supply bar and headquarters rule are full-width horizontal rules, for instance - so they carry measured bounds here.
 * <p>
 * Generated by {@code FragmentMeasurer}; do not edit. Keyed by graphic identifier, which is the fragment's file stem.
 */
public final class ModifierBounds {

    private static final Map<String, Rectangle2D> BOUNDS = Map.ofEntries(
        Map.entry("01021", new Rectangle2D(275, 267.61, 56.69, 94.96)),
        Map.entry("01041", new Rectangle2D(279, 267.61, 51.92, 94.96)),
        Map.entry("01042", new Rectangle2D(282, 432.13, 53.36, 89.38)),
        Map.entry("01051", new Rectangle2D(294, 264.61, 23.62, 94.96)),
        Map.entry("01052", new Rectangle2D(282, 434.13, 57.77, 89.38)),
        Map.entry("01061", new Rectangle2D(279, 272.13, 53.36, 89.38)),
        Map.entry("01161", new Rectangle2D(279, 267.61, 42.5, 94.96)),
        Map.entry("01171", new Rectangle2D(279, 267.61, 56.69, 94.96)),
        Map.entry("01181", new Rectangle2D(279, 267.61, 61.38, 94.96)),
        Map.entry("01191", new Rectangle2D(279, 267.61, 51.92, 94.96)),
        Map.entry("05012", new Rectangle2D(272, 432.61, 66.12, 94.96)),
        Map.entry("05112", new Rectangle2D(273.71, 433.13, 53.36, 89.38)),
        Map.entry("10092", new Rectangle2D(283, 431.61, 61.38, 94.96)),
        Map.entry("10142", new Rectangle2D(275, 430.51, 56.03, 93.84)),
        Map.entry("10261", new Rectangle2D(277.95, 270.32, 50.09, 91.61)),
        Map.entry("10482", new Rectangle2D(279, 432.61, 51.92, 94.96)),
        Map.entry("10542", new Rectangle2D(274.88, 431.32, 54.93, 91.61)),
        Map.entry("10552", new Rectangle2D(275, 431.32, 54.69, 91.61)),
        Map.entry("10562", new Rectangle2D(275, 433.32, 59.22, 91.61)),
        Map.entry("10582", new Rectangle2D(273.83, 433.32, 63.78, 91.61)),
        Map.entry("10601", new Rectangle2D(279, 266.61, 56.69, 94.96)),
        Map.entry("10622", new Rectangle2D(121, 442.52, 370, 5.28)),
        Map.entry("10941", new Rectangle2D(186.83, 292.78, 249.83, 52.35)),
        Map.entry("10981", new Rectangle2D(131.5, 342.5, 348, 5)),
        Map.entry("15041", new Rectangle2D(295, 269.83, 22.23, 89.38)),
        Map.entry("20012", new Rectangle2D(277, 432.83, 53.36, 89.38)),
        Map.entry("20022", new Rectangle2D(277, 432.83, 57.77, 89.38)),
        Map.entry("20032", new Rectangle2D(277, 432.83, 57.77, 89.38)),
        Map.entry("20042", new Rectangle2D(277, 432.83, 57.77, 89.38)),
        Map.entry("20062", new Rectangle2D(285, 433.13, 53.36, 89.38)),
        Map.entry("20072", new Rectangle2D(278, 434.13, 53.36, 89.38)),
        Map.entry("20121", new Rectangle2D(281, 270.83, 48.87, 89.38)),
        Map.entry("30012", new Rectangle2D(278, 432.83, 57.77, 89.38)),
        Map.entry("30052", new Rectangle2D(283, 434.83, 57.77, 89.38)),
        Map.entry("30072", new Rectangle2D(283, 434.83, 48.87, 89.38)),
        Map.entry("30082", new Rectangle2D(278, 434.83, 53.36, 89.38)),
        Map.entry("30092", new Rectangle2D(285, 434.83, 48.87, 89.38)),
        Map.entry("30112", new Rectangle2D(284, 429.78, 45, 100.55)),
        Map.entry("30122", new Rectangle2D(276, 432.83, 53.36, 89.38)),
        Map.entry("30171", new Rectangle2D(279, 271.83, 48.87, 89.38)),
        Map.entry("35022", new Rectangle2D(283, 434.83, 57.77, 89.38)),
        Map.entry("35062", new Rectangle2D(278, 432.83, 57.77, 89.38)),
        Map.entry("C1152", new Rectangle2D(278.03, 272.13, 53.36, 89.38)),
        Map.entry("C2118", new Rectangle2D(274, 430.61, 61.38, 94.96)),
        Map.entry("C2119", new Rectangle2D(272, 432.13, 66.64, 89.38)),
        Map.entry("C2121", new Rectangle2D(278, 430.61, 47.27, 94.96)));

    /**
     * The bounds of the fragment with this identifier, or {@link IconGeometry#OCTAGON} when it keeps within the octagon like the great majority.
     */
    public static Rectangle2D lookup(String graphicIdentifier) {
        return BOUNDS.getOrDefault(graphicIdentifier, IconGeometry.OCTAGON);
    }

    private ModifierBounds() {
    }

}
