modelFilePath: "/model-historical.yml"
modelSourceFile: "D:/git/jmsfx/jmsfx-tools/jmsfx-generator/src/main/resources/model-historical.yml"
outputDir: "D:/git/jmsfx/library/jmsfx-historical/src/main/java"
resourceDir: "D:/git/jmsfx/library/jmsfx-historical/src/main/resources"
iconPackage: "io.github.ctgnz.jmsfx.historical"
commonPackage: "io.github.ctgnz.jmsfx.historical.common"
amplifierPackage: "io.github.ctgnz.jmsfx.historical.amplifier"
countryCodeClass: "NatoCountryCode"
libraryPrefix: "Historical"
