modelFilePath: "/model-standard.yml"
outputDir: "D:/git/jmsfx/jmsfx-standard/src/main/java"
iconPackage: "io.github.ctgnz.jmsfx.standard"
commonPackage: "io.github.ctgnz.jmsfx.standard.common"
amplifierPackage: "io.github.ctgnz.jmsfx.standard.amplifier"
libraryPrefix: "Standard"
